### ISSUE TITLE
install guide?

### ISSUE THREAD

**Issue by RobotsAreCrazy** [mjakeman/extension-manager#1]
Hi,

would you mind giving a tutorial how to setup and install 
this please, learning linux so it would greatly help me?

going to use fedora

Thankyou

**Comment by RobotsAreCrazy** [comment]
What about manager updates, is that auto or do we have to do it manually?

**Comment by mjakeman** [comment]
It'll be manual for now. I'll probably look into putting this on flathub for the next release, so it'll be done automatically.

**Comment by mjakeman** [comment]
Extension Manager is now available on flathub! :tada:

I strongly recommend uninstalling the version from github and installing from flathub instead, as it will receive updates and improvements in the future.

Get it here: https://flathub.org/apps/details/com.mattjakeman.ExtensionManager

**Comment by vladaman** [comment]
I like to install apps using apt. Is there a repository?
