### ISSUE TITLE
Crash when browsing for extensions

### ISSUE THREAD

**Issue by tronta** [mjakeman/extension-manager#103]
When I want to install an extension and I go to the browse tab, the application crashes.

I tried to create a traceback and saw the following:
```
/usr/include/c++/11.2.0/string_view:233: constexpr const value_type& std::basic_string_view<_CharT, _Traits>::operator[](std::basic_string_view<_CharT, _Traits>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; std::basic_string_view<_CharT, _Traits>::const_reference = const char&; std::basic_string_view<_CharT, _Traits>::size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.
Aborted (core dumped)
```
I hope this helps somehow.

[debug_extension.txt](https://github.com/mjakeman/extension-manager/files/8031259/debug_extension.txt)

**Comment by mjakeman** [comment]
That's bizarre...

The crash implies something wrong with C++ strings, except as far as I know we don't use C++ anywhere in either the project or its dependencies, with the exception of Harfbuzz (the font shaping engine).

This line is also suspect:
```
** (extension-manager:2): DEBUG: 10:11:03.168: Found extension '(null)' with properties:
```

Just to confirm, this is v0.2.2 from flathub?

Could you provide the following info:
 - Distribution and version
 - GNOME Shell Version
 - Flatpak version (and also whether it's from distribution repo, ppa, or something else)
 - The system font (if you've changed it)

**Comment by tronta** [comment]
It seam's in generally work now, but not if a proxy is set, I'll see if there is already a bug.
