### ISSUE TITLE
Search does not to work with proxy

### ISSUE THREAD

**Issue by tronta** [mjakeman/extension-manager#106]
when VPN with proxy is activated, it does not find any extensions:
[debug_extension.txt](https://github.com/mjakeman/extension-manager/files/8053100/debug_extension.txt)

Version: 0.2.2
Ubuntu 20.04.3 LTS
Gnome: 3.36.8
Flatpak 1.6.5
Font (not changed): Ubuntu Regular

**Comment by rob-64** [comment]
Similar issue, without VPN..

Search does not work behind corporate HTTP_PROXY

**Comment by mjakeman** [comment]
Let's close this in favour of #192 since there's a bit more activity there
