### ISSUE TITLE
In Browse tab list Unsupported at botto of search result

### ISSUE THREAD

**Issue by igor2x** [mjakeman/extension-manager#108]
I installed development version of Ubuntu 22.04. I installedExtention-manager 0.2.2 from Flathub flatpak package.

This is feature request. Please move all of the Unsupported extensions at bottom of the list or say it differently first group by installation type:
- Install
- Installed
- Unsupported --> always at bottom

![image](https://user-images.githubusercontent.com/10895030/154533971-d98efaad-8989-408d-86a5-cd6d70970283.png)

**Comment by mjakeman** [comment]
While this would be nice, it isn't something we can easily do at the moment.

Search results are determined server-side on extensions.gnome.org and we simply parse and display them. A new API would need to be implemented inside extensions-web to let this happen cleanly. If that does happen, I'll happily add support for it here.

A similar feature is tracked here: https://gitlab.gnome.org/Infrastructure/extensions-web/-/issues/176. It isn't exactly what you're asking for, but is related.

**Comment by mjakeman** [comment]
Let's close this in favour of #114. It's not entirely the same, but I'd like to avoid manipulating search results as that'll get in the way of pagination.
