### ISSUE TITLE
Global toggle to enable/disable all extensions

### ISSUE THREAD

**Issue by bdaase** [mjakeman/extension-manager#11]
The normal extension app can do this. It's super helpful to debug extension issues.

**Comment by mjakeman** [comment]
Looks like there's a DBus property called `UserExtensionsEnabled` for the `org.gnome.Shell.Extensions` interface. I think simply binding that to a switch should be enough.

Although I'm not sure where to put it UI-wise, since it isn't very relevant to the Browse tab.

Thoughts?

**Comment by bdaase** [comment]
Hmm, intuitively I would have said, let's put in the header bar.
But now I also see your concern regarding the `Browser` tab. 
Still, maybe the header bar still is the best location nonetheless?

**Comment by mjakeman** [comment]
I think for the mean time, having it in the header bar is fine.

I've noticed a few comments where there is some confusion about why extensions are not working (when they are in fact disabled), so having this feature sooner rather than later is ideal.
