### ISSUE TITLE
Add option to hide unsupported extension

### ISSUE THREAD

**Issue by 0x6e656b6f** [mjakeman/extension-manager#114]
Hiding unsupported extension would make installing extension quicker and make the UI cleaner especially when your search query resulted in almost all unsupported extension.

**Comment by mjakeman** [comment]
Agreed, it's a poor user experience having many of the top results being uninstallable.

Unfortunately, this isn't trivial to do on the app-side as our search results come directly from EGO. There's an upstream issue tracking support for this: https://gitlab.gnome.org/Infrastructure/extensions-web/-/issues/176

If that gets implemented, I'll add the relevant bits here to support it. If there isn't any activity on that issue after our 0.3 release, I might have a crack at it myself.

**Comment by mjakeman** [comment]
This seems like it may actually be supported:

https://extensions.gnome.org/#shell_version=42

I wonder if we can use this.
