### ISSUE TITLE
Use hosted weblate for managing translations

### ISSUE THREAD

**Issue by mjakeman** [mjakeman/extension-manager#116]
Currently adding/updating translations has a non-trivial barrier to entry. We can make this far more straightforward through a hosted PO editor.

[Weblate](https://weblate.org/en/hosting/) offers free hosting for FOSS projects provided they meet the criteria:

- [X] Translated content has to be released under a license approved by OSI or recognized as libre by FSF.
- [X] All the source code has to be publicly available in a supported version control system.
- [X] Translations have to be in the same repository as the source code, or under the same project/organization as the source code repository.
- [X] Using Weblate has been approved by the upstream project.
- [ ] Mention you use Weblate for translations in the README. It’ll attract new translators and also help Weblate to be free for more projects.
- [ ] The project has had active development for at least three months.

Unfortunately, the project has only existed for two months. In mid-April, we should be eligible for free hosting.

**Comment by mjakeman** [comment]
I've started investigating Weblate and set it up to automatically push/pull from the repo.

Project: https://hosted.weblate.org/projects/extension-manager/extension-manager/

**Comment by mjakeman** [comment]
Not sure there's that much benefit in using weblate. Maybe it's worth exploring down the line but for now GitHub-based PRs seem to work fine.

**Comment by musiclover382** [comment]
An input from a translator. Using Weblate does, indeed, speed up the translation process and in a lot of cases it will improve translation quality since I will never make a PR just to change 1 string, but if while using exm I notice a string is wrong I can just head over to Weblate and edit that one string.
