### ISSUE TITLE
Distinguish between manually installed and built-in extensions

### ISSUE THREAD

**Issue by bdaase** [mjakeman/extension-manager#12]
Just like the normal app. Helps to quickly see which extensions can be uninstalled from the app.

**Comment by mjakeman** [comment]
Agreed.

We already do this somewhat - user installed extensions show the 'Remove' button, while system extensions do not.

The extensions view is currently one large `GtkListBox`. I think a sensible first step would be to split the extensions model into 'User Extensions' and 'System Extensions'. Then we'd simply display them separately.
