### ISSUE TITLE
Search always returns "No Results Found"

### ISSUE THREAD

**Issue by distefam** [mjakeman/extension-manager#167]
If I search for anything, even an extension that shows up in the Browse pane, Extension Manager returns "No Results Found" after waiting for the spinner to finish when I input my query. I am running version 0.3, which is installed on Fedora 35 via the Flatpak package from Flathub.

**Comment by mjakeman** [comment]
Hey @distefam, are you still having this issue?

There was an outage for the GNOME Extensions website around the same time this was opened, which could be a likely cause. Also, are you using a VPN or Proxy by any chance?

**Comment by distefam** [comment]
Hi @mjakeman, thank you for checking in about this. You are indeed correct, it was the outage. Sorry for the false alarm!

**Comment by mjakeman** [comment]
No worries - great to hear it's resolved :slightly_smiling_face:
