### ISSUE TITLE
Bad looking on Ubuntu 22.04

### ISSUE THREAD

**Issue by leoheck** [mjakeman/extension-manager#171]
Hello there, this is the look of Extension Manager on my pre-released Ubuntu 22.04
I am using the dark theme by the way.

- Dark theme is not being applied even when forcing using the menu on the top
- Top bar is stretched.
- Icons on the top bar are glued close to the text
- List items are squished and not well formatted

![image](https://user-images.githubusercontent.com/1277920/162224522-ca7c646f-de73-42e3-9acb-692b5a115f67.png)
![image](https://user-images.githubusercontent.com/1277920/162224919-b348a5ea-3b1e-4a52-b7f7-d07cd7912924.png)

What do I do to check if this is being caused by Ubuntu or a missing config file? 

Do you know any workaround for any of these issues?

**Comment by mjakeman** [comment]
Hi, this is definitely a theme related issue.

Extension Manager uses libadwaita for many of its widgets, which bundles a theme ('Adwaita') along with the application to avoid issues like these. Somehow, it's being overridden with the 'Default' theme that comes with GTK 4.

Could you open the GTK Inspector (Ctrl+Shift+D) and check what theme is set (under Global->Settings)?

Also, can you provide the following information:
 - Where did you get the app from? (Flathub, Repos, etc)
 - Have you set a custom theme? If so:
   - Do you have the `GTK_THEME` environment variable set?
   - Do you have a custom `gtk.css` file set?

**Comment by leoheck** [comment]
> Could you open the GTK Inspector (Ctrl+Shift+D) and check what theme is set (under Global->Settings)?

Oh, this is a nice thing.

This is the whole info on this page

![image](https://user-images.githubusercontent.com/1277920/162473381-f16b9d78-4398-4442-aad9-7a827f79a518.png)

> Where did you get the app from? (Flathub, Repos, etc)

I don't remember. But this may help you give some idea of that.
![image](https://user-images.githubusercontent.com/1277920/162473808-1f57b579-b3bb-4afc-9305-d4d0418a1d26.png)

> Have you set a custom theme? If so:

No, I am using it by default. But it may have issues since this version of the ubuntu was not released yet. It is going to be released by April/21

> Do you have the GTK_THEME environment variable set?

No, this variable is empty

> Do you have a custom gtk.css file set?

I don' t have, maybe this Ubuntu version has. How do I check this?

**Comment by LechintanTudor** [comment]
I have the same issue on Fedora 35.

**Comment by mjakeman** [comment]
> I have the same issue on Fedora 35.

Uh oh. I'm running Fedora 35 and definitely cannot reproduce.

Could you both try install one or two of the following apps (from flathub) and see if they are also affected? These apps similarly use libadwaita, and so should also be affected by any theming issues:
 - [Kooha](https://flathub.org/apps/details/io.github.seadve.Kooha)
 - [GNOME Text Editor](https://flathub.org/apps/details/org.gnome.TextEditor)
 - [rnote](https://flathub.org/apps/details/com.github.flxzt.rnote)
 - [Fragments](https://flathub.org/apps/details/de.haeckerfelix.Fragments)

This should help narrow down whether it's an issue on our end, with libadwaita apps generally, or a problem with your system configuration. Thanks!

**Comment by leoheck** [comment]
I will give it a try in some days, definitely.

But some days ago (some Ubuntu updates before) the new text editor was looking good. However the RNote does not look good. Dark theme does not work there too. 

I can share screenshots when I am able to test those apps. I am replying on my smartphone now.

**Comment by LechintanTudor** [comment]
Here is a screenshot of flatpak Fragments.
![fragments](https://user-images.githubusercontent.com/52962370/163543331-bbb24bfc-a8f2-4551-be06-c9191abd8c45.png)

And here is a screenshot of rpm Text Editor.
![text_editor](https://user-images.githubusercontent.com/52962370/163543468-fa648f8b-3190-44ca-863d-0f22e13c3630.png)

It seems like something is overriding the theme for flatpak applications. I ran `sudo flatpak override --reset` but the issue still persists.

**Comment by ScribeAwoken** [comment]
Hey, so I found something that might be relevant:

So it's possible to apply a custom theme to Libadwaita apps by adding a `gtk.css` file to `~/.config/gtk-4.0`

It seems like if you pull the `gtk.css` from *any* GTK 4 theme and plonk it down in `~/.config/gtk-4.0`, it causes issues with libadwaita apps having unusually thick headerbars. This one has some particularly ugly results because of the switch in the headerbar.

**Comment by LechintanTudor** [comment]
I ran `sudo find / -name gtk.css`
```
/usr/share/themes/Adwaita-dark/gtk-3.0/gtk.css
/usr/share/themes/Adwaita/gtk-3.0/gtk.css
/usr/share/themes/HighContrast/gtk-3.0/gtk.css
/usr/share/inkscape/themes/Minwaita-Inkscape/gtk-3.0/gtk.css
/usr/share/inkscape/themes/Minwaita-Inkscape-Dark/gtk-3.0/gtk.css
```
There is no mention of gtk-4.0, so something else must be the issue...

**Comment by ScribeAwoken** [comment]
okay weird

because I only get this issue when I have a custom style sheet applied. If I use Adwaita or a style sheet that only changes the color scheme, I don't have this issue.

**Comment by mjakeman** [comment]
> @ScribeAwoken It seems like if you pull the gtk.css from any GTK 4 theme and plonk it down in ~/.config/gtk-4.0, it causes issues with libadwaita apps having unusually thick headerbars. This one has some particularly ugly results because of the switch in the headerbar.

Yeah, this is expected as most themes do not support/conflict with libadwaita.

It's strange (and concerning) to see this issue happening with no theme set however :confused: 

> @LechintanTudor There is no mention of gtk-4.0, so something else must be the issue...

The only thing I can think of is that `GTK_THEME` is somehow set. Can you run the following commands and tell me what the output is?

```txt
# open a new shell inside the flatpak sandbox
flatpak run --command=sh com.mattjakeman.ExtensionManager

# print out the current theme
echo $GTK_THEME

# set the theme to a broken one
export GTK_THEME=Default

# run extension-manager - it should look broken!
extension-manager

# unset the theme
unset GTK_THEME

# run extension-manager - it should look correct!
extension-manager

# exit the sandbox shell
exit
```

**Comment by LechintanTudor** [comment]
@mjakeman That was the issue!
Inside the flatpak sandbox, GTK_THEME was set to Adwaita-dark and the app looked broken. After I unset the GTK_THEME the app looked as expected.

One problem is that the GTK_THEME is somehow reset to Adwaita-dark after I leave the sandbox shell. I tried running `sudo flatpak override --unset-env=GTK_THEME` but GTK_THEME is still set to Adwaita-dark.

**Comment by leoheck** [comment]
Great, unsetting this `GTK_THEME` has fixed it for me. This is the answer I was looking for.  Now the question, why it was wrongly set in the first place? Maybe the Ubuntu team is doing something nasty in the pre-released Ubuntu 2022.04...
```
sudo flatpak override --unset-env=GTK_THEME
```

![image](https://user-images.githubusercontent.com/1277920/163822638-1cabc110-b3a7-4729-b81e-8ed9247dd77a.png)
![image](https://user-images.githubusercontent.com/1277920/163822946-d5d77074-ec86-4a81-ae5a-cab9ef0f9810.png)
![image](https://user-images.githubusercontent.com/1277920/163823046-8ee70bec-5216-4dc2-a02b-ea094740ae81.png)

**Comment by LechintanTudor** [comment]
The `GTK_THEME` variable was set to `Adwaita:dark` in a file found in `~/.local/share/flatpak/overrides/`. After I removed the override from that file, the app used the correct theme.

**Comment by mjakeman** [comment]
> @LechintanTudor: The GTK_THEME variable was set to Adwaita:dark in a file found in ~/.local/share/flatpak/overrides/. After I removed the override from that file, the app used the correct theme.

Great to hear - glad it's resolved!
