### ISSUE TITLE
extensions not following system wide theme

### ISSUE THREAD

**Issue by jinko690** [mjakeman/extension-manager#178]
Hey,
I am trying to apply themes but this app doesn't follow the system theme. Any help would be appreciated.
Running fedora 35.

**Comment by mjakeman** [comment]
Hi, thanks for the interest

Extension Manager does not 'officially' support theming - see https://github.com/mjakeman/extension-manager/issues/20 for more information.

That being said, you can still override the theme if you really want to (although it might look broken). There's a short explanation in [this reddit thread](https://www.reddit.com/r/gnome/comments/tp3v7d/theming_in_libadwaita_is_pretty_nice/i28pug0/) which might be helpful. Best of luck!
