### ISSUE TITLE
Extension with missing title

### ISSUE THREAD

**Issue by leoheck** [mjakeman/extension-manager#179]
There is an extension that does not have a Title. Is this a bug in the extension itself or with the Extension Manager?
If the Extensions does not have an important field, I can file a bug report there. 
![image](https://user-images.githubusercontent.com/1277920/163823526-1c772d18-d207-4971-9921-b21f6fcc0060.png)

**Comment by mjakeman** [comment]
Duplicate of #173 which was fixed in #175 

Will be included in the next minor update :)

**Comment by leoheck** [comment]
Ah, nice. Thank you for the feedback @mjakeman
