### ISSUE TITLE
Support Ubuntu 22.04 accent colors on Flatpak version

### ISSUE THREAD

**Issue by santiagofn** [mjakeman/extension-manager#187]
Ubuntu 22.04 introduced a new 'accent colors' palette that applies the chosen one to the whole system (["It's FOSS" article about this](https://news.itsfoss.com/ubuntu-22-04-accent-color/)).

Sadly, Extension Manager doesn't seem able to use the color on the Flatpak version:

![image](https://user-images.githubusercontent.com/8375708/165862453-8a83bcf9-75fd-492d-8761-d73235428f18.png)

The Deb version seems to work fine:
![image](https://user-images.githubusercontent.com/8375708/165864669-eb006342-3d43-4d25-8bd7-c32f47bb08dc.png)

**Comment by mjakeman** [comment]
This is not a bug with extension manager but rather with how Ubuntu implements accent colours. I would open an issue against Yaru (or wherever the accent colours are implemented) regarding it not affecting flatpak apps.

As far as I can tell, accent colours are simply GTK themes, meaning there's no way for apps to be aware of which colour is set. If libadwaita ever gains API for this I'm happy to support it.
