### ISSUE TITLE
Allow loading more than 10 results

### ISSUE THREAD

**Issue by szbergeron** [mjakeman/extension-manager#191]
If a lot of extensions contain a searched term, or if I'm just browsing through the most popular extensions, it would be nice to be able to load more results than the first 10 returned.

Could be accomplished by a "load more" button, or a scroll trigger at end of list, or even a page structure that indicates how many matching results there are.

**Comment by Battler624** [comment]
Literally used the extension manager today and this is the first thing that came to mind. I dont know all the extensions I would want and would like to browse sometimes.

That and adding a "Show Unsupported" button with a default of Off.

**Comment by celsotavaresdev** [comment]
> Yep, pagination is planned for 0.4. This depends on extensions.gnome.org actually exposing this information via the API,

I think it's possible via the API, using the `numpages` key. For example, searching for "terminal" returns `numpages: 4`, so we can use the query `page` with the value 1 ~ 4.

https://extensions.gnome.org/extension-query/?search=terminal&page=4

**Comment by mjakeman** [comment]
> I think it's possible via the API, using the numpages key. For example, searching for "terminal" returns numpages: 4, so we can use the query page with the value 1 ~ 4.

Ah great! I was looking for something like that.
