### ISSUE TITLE
the global toggle scales with font size

### ISSUE THREAD

**Issue by doppelhelix** [mjakeman/extension-manager#193]
![Bildschirmfoto vom 2022-05-08 18-19-44](https://user-images.githubusercontent.com/4622871/167305355-94b14e56-23b7-4489-9934-71e1e3ea9ca3.png)
Cantarell with font size 17
not sure if this should be a thing

**Comment by mjakeman** [comment]
Good catch - that doesn't look right.

The toggle is being moved in v0.4 (as part of #164) so I'll close this in favour of adding a note to that issue.
