### ISSUE TITLE
Feature Request: Show cog (settings) for installed apps in browse view

### ISSUE THREAD

**Issue by vixalien** [mjakeman/extension-manager#197]
The settings button is only shown in the "Installed" tab. It would be nice to also view it while browsing the extensions. Like modify settings just after installing.

**Comment by vixalien** [comment]
Thanks. Also, very good work.

**Comment by mjakeman** [comment]
So this is actually quite a bit harder than it seems. We'll need a way to combine information from the user's computer and the internet in a single view, which we can't do right now.

Let's instead have this done as part of the redesign in 1.0

**Comment by vixalien** [comment]
Hey @mjakeman here are a couple of other things that I thought you'd consider, but I don't want to create a lot of issues and dont know if they are considered/implemented.

- Search in installed extensions list
- Not sorting by activated/disactivated because when you deactivate an app, the UI jumps

**Comment by mjakeman** [comment]
Hi @vixalien 

> Search in installed extensions list

See #8 

> Not sorting by activated/disactivated because when you deactivate an app, the UI jumps

In the menu you can disable 'Sort By Enabled' and it will then sort extensions alphabetically.

**Comment by vixalien** [comment]
Thanks. A final suggestion would be to show progress when downloading 3xtesions because right now you don't know if you misclicked the button. I know extensions are only a few kilobytes so a full featured progress bar like in software shouldn't be needed, greying the button and changing the text tl "Installing..." should do the trick.

Thanks for your work too

**Comment by mjakeman** [comment]
Now part of #67 

(WIP version #517)
