### ISSUE TITLE
Check whether unzip is installed/available before installing extensions

### ISSUE THREAD

**Issue by pos-ki** [mjakeman/extension-manager#198]
Recently I tried to do a very minimal installation of Fedora, and there were therefore some relatively basic packages missing.

After clicking "Install" in the app to install an extension, the usual GNOME prompt to confirm installing is displayed, and once it is confirmed, the "Install" button of the extension does _not_ become grayed out as it should. The folder for the extension is created normally in `~/.local/share/gnome-shell/extensions`, but the created folder is left empty (nothing is unpacked into it). Crucially, no error or indication is displayed whatsoever, making it rather tedious to figure out what the problem is. 

Installing `unzip` with `dnf` (on Fedora) solves the problem.

Would it be possible to first check whether `unzip` is installed before installing extensions (or rather check whether the command `unzip` is available)? I feel it would be really useful to show an error and instruct the user to install the package first before installing extensions.

**Comment by mjakeman** [comment]
Hi, thanks for the report

Extension Manager, contrary to its name, does not actually manage the installation of extensions directly. Rather we communicate with GNOME Shell and send various requests to install or modify installed extensions similar to how the browser extension works.

I don't think this is an issue on our side. If anything, I would say it's a packaging error on Fedora as GNOME Shell should not be installable without unzip, or be designed to gracefully fail without it. I would recommend opening an issue on the fedora bugzilla (see [here](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/) and see if unzip can be included in as a dependency of GNOME Shell.

One thing we can do to improve the situation is to properly forward errors from GNOME Shell to the user. That's tracked in #31.
