### ISSUE TITLE
Respect system GTK theme

### ISSUE THREAD

**Issue by OlegKrikun** [mjakeman/extension-manager#20]
Hi! Thanks for the app!

Any way for the application to support the system GTK theme?

It looks bad to me compared to the rest of the native apps =(

<img src="https://user-images.githubusercontent.com/429351/149162124-ab7c63a8-9fb6-4ab5-b88d-64e8c5ec52c4.png" width=350 />

**Comment by tuxfollower** [comment]
I think that's impossible because it uses libadwaita which doesn't respect GTK themes. That's not a project specific problem but a problem you're gonna have more and more because of gnome apps switching to libadwaita. So you'd better to like adwaita :)

**Comment by OlegKrikun** [comment]
Look like it's right time to modify libadwaita, instead of installing custom GTK theme =)))
