### ISSUE TITLE
IDEA: add a manual update button for each installed extension

### ISSUE THREAD

**Issue by alexsch01** [mjakeman/extension-manager#203]
Would it be possible to have a manual update button for each extension that the user installed? I don't know if reinstalling an extension keeps the user's config for that extension, but this would be very useful for people who don't want the default Gnome Extensions app also installed

**Comment by alexsch01** [comment]
This would help users affected by https://github.com/mjakeman/extension-manager/issues/165 until it possibly gets fixed in Gnome

**Comment by mjakeman** [comment]
I'm not sure if I want to go down this route as it feels like a fairly hack-ish solution.

Regarding updates being broken, I've started asking around and the idea at the moment is to patch-out the check using  a special "Extension Manager Integrations" plugin. See https://github.com/mjakeman/extension-manager/issues/165#issuecomment-1149221761 for info. I think if that's in-place, then this wouldn't be needed.

**Comment by alexsch01** [comment]
@mjakeman Totally agree, the plugin idea is so much better
