### ISSUE TITLE
Inconsistent headerbar height

### ISSUE THREAD

**Issue by bluej121999** [mjakeman/extension-manager#204]
The headerbar does not seem to match its vertical height, with any other apps on my system. Running gnome 42, with an assortment of GTK3, GTK4 and libadwaita apps.

![Screenshot from 2022-06-02 04-23-10](https://user-images.githubusercontent.com/69988160/171618813-f0abc9df-eafd-4548-a7f6-093dab2327cf.png)

**Comment by bluej99** [comment]
App on the left is Epiphany or Gnome Web. I tested with almost every application I have, and the extension manager is just slightly bigger than the rest. Could this be related to font sizing?

Again, other apps also have font in their headerbars and they maintained consistent height. For reference, I changed the font from Catarell 11 to Noto Sans 12

**Comment by mjakeman** [comment]
Is that the GTK 4 version of Web or do you have a theme applied?

The font seems like a likely culprit. I'll try out a few different settings and see if it's something fixable on our end.

**Comment by bluej99** [comment]
That is a theme called adw-gtk3-dark, it's a GTK3 theme that closely resembles libadwaita:dark. Just to make sure i tested without tiling, and it does seem like it's just bigger by default.

 Font seems to be it, but since font settings aren't user facing options ( I had to use gsettings ) I'm starting to wonder if this might be an upstream issue?

**Comment by mjakeman** [comment]
Is the issue still there using stock Adwaita?

Can you try a few of the following apps and see if they are also larger? These apps use libadwaita so they should be stylistically identical to Extension Manager (should help narrow down if we're doing something unique):
 - [Kooha](https://flathub.org/apps/details/io.github.seadve.Kooha)
 - [GNOME Text Editor](https://flathub.org/apps/details/org.gnome.TextEditor)
 - [rnote](https://flathub.org/apps/details/com.github.flxzt.rnote)
 - [Fragments](https://flathub.org/apps/details/de.haeckerfelix.Fragments)

**Comment by bluej99** [comment]
Done.

Kooha does not have a visible headerbar separation but the Extension Manager separation does seem to clip into Kooha's widgets ever so slightly.

Extension Manager is still larger than Gnome Text Editor, rnote and Fragments. 

Do you know any other libadwaita app using the same (tab or switch?) widget you are using in the headerbar? This might be an upstream widget issue.

**Comment by mjakeman** [comment]
> Kooha does not have a visible headerbar separation but the Extension Manager separation does seem to clip into Kooha's widgets ever so slightly.

Whoops, forgot about that

> Extension Manager is still larger than Gnome Text Editor, rnote and Fragments.

This will definitely be an issue on our side then. I think we're probably missing a `valign` setting somewhere.

> Do you know any other libadwaita app using the same (tab or switch?) widget you are using in the headerbar? This might be an upstream widget issue.

As part of the GNOME Circle review, it's been requested that the headerbar switch be moved inside the main view to properly give it context (#164). Hopefully that change will fix this for free.

**Comment by bluej99** [comment]
Yeah moving the widget out of the headerbar should probably do it. Though, a lot of the newer apps are implementing tabs and switching into the headerbar, I'm not sure if they will ever get accepted into the GNOME Circle, but it is a trend.

Regardless, I do wish to see this in the GNOME Circle, its the first thing I install on a GNOME system.

**Comment by bluej121999** [comment]
I have found another app that exhibits the same behavior: pamac. That app also has a headerbar switch unsurprisingly.
