### ISSUE TITLE
Unable to enable unsupported extensions

### ISSUE THREAD

**Issue by mjakeman** [mjakeman/extension-manager#209]
> Hello @mjakeman , thank you for the great plugin it is amazing :pray: 
>
> It seems I'm able to install unsupported extension, but I'm unable to enable them, is that the intended behavior? Do you know a way I can force the enable? I'm guessing they work even if wrong version
>
> ![Screenshot from 2022-05-30 21-10-29](https://user-images.githubusercontent.com/657731/171049255-d6c2f255-882d-4efa-92eb-067416608f77.png)

_Originally posted by @dubreuia in https://github.com/mjakeman/extension-manager/issues/136#issuecomment-1141424375_

**Comment by mjakeman** [comment]
Hi @dubreuia, I'll look into this a bit more for 1.0

Does this issue still exist on a newer version of GNOME Shell? I think the latest version should be 42.4.

**Comment by p3732** [comment]
Having a way to easily allow using extensions after a shell version update would be a superb! I think many non-tech-savy people would be very happy to have an easy solution for that.

**Comment by mjakeman** [comment]
Hi @dubreuia, does this still happen on v0.4.3? We've done some reworking of how the app handles local extensions so hopefully it is fixed.
