### ISSUE TITLE
Phase out theme switcher

### ISSUE THREAD

**Issue by bordam** [mjakeman/extension-manager#218]
I think the theme switcher in the hamburger menu could be improved mimicking what other gnome apps like the text editor do.
![immagine](https://user-images.githubusercontent.com/95233098/176125352-59254d27-f691-4e1e-85b5-353ec959b834.png)

**Comment by mjakeman** [comment]
Yep, makes sense.

As far as I know, this isn't standardised (there's no widget/s for it in libadwaita) so we'll need to find an implementation and make sure we can legally reuse it. Since everything is GPL'd it should be fine.

I'll mark this "help wanted" for now, patches welcome.

**Comment by A6GibKm** [comment]
I think that one the contrary, the app shouldn't have a color scheme selector at all and follow the system color scheme, the only apps where it makes sense are on heavy text-based apps like a IDE.

**Comment by mjakeman** [comment]
> I think that one the contrary, the app shouldn't have a color scheme selector at all and follow the system color scheme, the only apps where it makes sense are on heavy text-based apps like a IDE.

Yeah I agree. I'm leaning towards removing it for 1.0 (circa GNOME 44), as the freedesktop dark preference seems pretty widely adopted at this point.
