### ISSUE TITLE
SSL Handshake failure while installing extensions

### ISSUE THREAD

**Issue by dinhokusanagi** [mjakeman/extension-manager#219]
** (extension-manager:2): CRITICAL **: 02:51:28.526: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:org.gnome.Shell.ExtensionError: Unexpected response: SSL handshake failed

**Comment by mjakeman** [comment]
Could you provide:
 - Which operating system you are on? (e.g. Fedora, Ubuntu)
 - Which version of the application? (v0.3.1)
 - Where you got it from? (Flatpak, Ubuntu repos, etc)

**Comment by dinhokusanagi** [comment]
Fedora silverblue
(v0.3.1)
Flatpak

**Comment by kostadin04** [comment]
I am getting something similar on Fedora Silverblue. Latest version of the application, got it from Flathub.

`GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:org.gnome.Shell.ExtensionError: Unexpected response: Bad Request`

**Comment by pc00per** [comment]
Same here
`GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:org.gnome.Shell.ExtensionError: Unexpected response: Bad Request`
arch-5.18.9 / AUR / extension-manager-0.3.1

**Comment by PrincessAkira** [comment]
> I am getting something similar on Fedora Silverblue. Latest version of the application, got it from Flathub.
> 
> `GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:org.gnome.Shell.ExtensionError: Unexpected response: Bad Request`



> Same here `GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:org.gnome.Shell.ExtensionError: Unexpected response: Bad Request` arch-5.18.9 / AUR / extension-manager-0.3.1

try this you both as seen in #224 

https://github.com/mjakeman/extension-manager/issues/224#issuecomment-1178166240

**Comment by pc00per** [comment]
> try this you both as seen in https://github.com/mjakeman/extension-manager/issues/224
I'm sorry but I'm not downgrading anything. Lemme know when the extension gets fixed on gnome newer versions.

**Comment by mjakeman** [comment]
Let's keep this issue focused on the SSL Handshake failure issue. If extensions have randomly stopped working after an update, you want #224 instead.

**Comment by dinhokusanagi** [comment]
the GNOME Shell 42.2 version has this problem, I saw in the other thread that above this version it was also

**Comment by pc00per** [comment]
Update: It's fixed in 42.3.1

**Comment by dinhokusanagi** [comment]
That's great
