### ISSUE TITLE
No extensions are installing

### ISSUE THREAD

**Issue by NavTech270** [mjakeman/extension-manager#224]
The install button does not actually install anything on my system. My distro is Fedora 36 and I used Flatpak to install extension manager. I've even tried manually installing extensions from the web but the browser doesn't install anything either.

**Comment by J0shuaT** [comment]
> The install button does not actually install anything on my system. My distro is Fedora 36 and I used Flatpak to install extension manager. I've even tried manually installing extensions from the web but the browser doesn't install anything either.

I have the SAME problem. I thought it was just me. For some reason, I am also having trouble installing extensions via browser.

**Comment by NavTech270** [comment]
Oh damn! I hope it's fixed soon. It was so random. Let me know if it starts working for you again, @J0shuaT

**Comment by rafal06** [comment]
> It actually might be a problem with Fedora 36

It works without any problems on my system. Also Fedora 36, and Extension Manager flatpak.

**Comment by J0shuaT** [comment]
@rafal06 Is the extension manager up to date? Are all your fedora packages up to date too? I'm using a clean install of fedora

**Comment by rafal06** [comment]
@J0shuaT I've updated my system 2 days ago, but it looks like there are [some updates](https://user-images.githubusercontent.com/70489677/177843833-7736b69b-b88f-4c4c-a8fb-d30e34c5701c.png) available. Also, Extension Manager is on the newest version (0.3.1)

**Comment by J0shuaT** [comment]
@NavTech270 @rafal06 It turns out gnome-shell _is_ the problem! I downgraded with `sudo dnf install gnome-shell-42.0-3.fc36` and now installing extensions from extension manager works fine.

**Comment by NavTech270** [comment]
Yeh that did the trick @J0shuaT. I was quite surprised! Maybe extension manager is not compatible with gnome version 42.3.1 then. This might be something the developer needs to look into @J0shuaT @mjakeman

**Comment by J0shuaT** [comment]
@NavTech270 I'm glad it worked for you! I don't think it is extension manager problem, because installing from a web browser didn't work either. It might be a bug with the latest gnome-shell on fedora.

**Comment by J0shuaT** [comment]
@Rend0e try downgrading to an earlier version of `gnome-shell`.

**Comment by NavTech270** [comment]
> @NavTech270 I'm glad it worked for you! I don't think it is extension manager problem, because installing from a web browser didn't work either. It might be a bug with the latest gnome-shell on fedora.

Let's see if the next version of gnome shell fixes this issue @J0shuaT

**Comment by PrincessAkira** [comment]
> I'm getting the same issue (Fedora 36 and recent update). Not sure if it's necessary but this is the error I get: `** (extension-manager:2): CRITICAL **: 21:57:28.899: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:org.gnome.Shell.ExtensionError: Unexpected response: Bad Request`

Small heads up here. Im on a fresh Arch (latest and updated), which i reinstalled about 6 times now, and have the EXACT same thing happen to me everytime. I thought i was going crazy at first, because i couldnt find anything about this.
this is how my website looks, nor can i install via Extension Manager.
![image](https://user-images.githubusercontent.com/45071533/177956688-ea996f2c-19a5-4bee-aee4-74667a11f345.png)

**Comment by NavTech270** [comment]
Best to just wait for the next update of Gnome at this point. Do not install Arch for a 7th time! @PrincessAkira

**Comment by NavTech270** [comment]
> @Quispie try downgrading gnome-shell with `sudo dnf install gnome-shell-42.0-3.fc36`. Then restart your computer and try installing an extension

People who are in need of installing an extension, just follow these steps above from @J0shuaT but with the package manager corresponding to your distro 👍

**Comment by julianfairfax** [comment]
I'm also having this issue on Arch

**Comment by solomontaiwo** [comment]
I'm also having this issue on Fedora 36 and gnome-shell 42.3.1, downgrading fixed it.

**Comment by mjakeman** [comment]
Upstream issue: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5622

Looks like a problem with the website not recognising longer version numbers, so it will affect everyone running version 42.3-1.

This should get fixed for free whenever the website is updated. In the meantime, I would downgrade your gnome-shell package as described above and also report it to your distro bugtracker.

**Comment by PrincessAkira** [comment]
> Upstream issue: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5622
> 
> Looks like a problem with the website not recognising longer version numbers, so it will affect everyone running version 42.3-1.
> 
> This should get fixed for free whenever the website is updated. In the meantime, I would downgrade your gnome-shell package as described above and also report it to your distro bugtracker.

we on arch are forced to wait anyways, since theres no downgrade package, that i found atleast.
but good to know they know about this

**Comment by julianfairfax** [comment]
> > Upstream issue: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5622
> > Looks like a problem with the website not recognising longer version numbers, so it will affect everyone running version 42.3-1.
> > This should get fixed for free whenever the website is updated. In the meantime, I would downgrade your gnome-shell package as described above and also report it to your distro bugtracker.
> 
> we on arch are forced to wait anyways, since theres no downgrade package, that i found atleast. but good to know they know about this
> 

https://github.com/archlinux-downgrade/downgrade

**Comment by NavTech270** [comment]
It's working now on Gnome version 42.3.1!! @mjakeman
