### ISSUE TITLE
Wrong cursor theme on Wayland

### ISSUE THREAD

**Issue by caioolivv** [mjakeman/extension-manager#227]
Extension manager doesn't follow cursor theme when on wayland.

Screenshot on Wayland:
![Screenshot from 2022-07-12 00-54-04](https://user-images.githubusercontent.com/38115797/178405505-4cb53ad8-c939-4d61-9e2f-e9f3165d898a.png)

Screenshot on X:
![Screenshot from 2022-07-12 00-54-59](https://user-images.githubusercontent.com/38115797/178405513-adfc1343-b602-4ac7-abd5-93d28fcd2768.png)

I've seen this on both my desktop and notebook (both on Fedora 36).

**Comment by caioolivv** [comment]
This happens when launched from app drawer and from pop-launcher, but not when launched from terminal.

**Comment by mjakeman** [comment]
Does this happen with other flatpak applications (particularly those that use libadwaita)? It seems like a known issue with flatpak.

**Comment by caioolivv** [comment]
Yeah, I'm pretty sure it was that flatpak issue. Still, it's weird that it happened on wayland but not on X, other apps that had this problem happend on both I think.

**Comment by mjakeman** [comment]
I'm not sure there's much we can do here. I think reporting this against flatpak is a good idea.

Maybe asking on the #flatpak matrix channel would help?
