### ISSUE TITLE
QUESTION: does it support CLI too?

### ISSUE THREAD

**Issue by krishnaTORQUE** [mjakeman/extension-manager#229]
Does it support CLI too?
I mean, can I use this tool to install extensions from terminal?

E.g.
```shell
gnome-shell-extension-manager install extension-uuid
```

**Comment by mjakeman** [comment]
Hi, there's nothing like that at the moment. I'm open to supporting it if someone shows up with patches, but due to the way installing works, the user will still need to interact with the GNOME Shell pop-up, so it won't be truly 'headless'.

Closing in favour of #172
