### ISSUE TITLE
Cannot install extensions on gnome 42

### ISSUE THREAD

**Issue by GoMapur** [mjakeman/extension-manager#238]
Seeing this error in console

`GDBus.Error:org.gnome.Shell.ExtensionError: Child process exited with code 10`

Do you have an idea what is this error?

**Comment by mjakeman** [comment]
I've honestly never seen that before... Does installing extensions work via the website?

That should help us narrow things down a bit.

**Comment by mjakeman** [comment]
@GoMapur Is this still an issue with 0.4?

If so, can you attach the error that will (hopefully) be displayed?

**Comment by GoMapur** [comment]
Hi, I still see this result, let me post more details on this later today

**Comment by GoMapur** [comment]
Hello, the update resolved the issue, I will close this thread as it is not appearing now. Thank you for the support!
