### ISSUE TITLE
Missing glib2 dependency.

### ISSUE THREAD

**Issue by patlefort** [mjakeman/extension-manager#255]
```
../extension-manager/src/local/shell-dbus-interface.c:17:12: fatal error: gio/gunixfdlist.h: No such file or directory
   17 | #  include <gio/gunixfdlist.h>
      |            ^~~~~~~~~~~~~~~~~~~
```

That file is part of glib2. I don't know how meson work but I'm assuming that a dependency on it is missing. More specifically what is defined in the pkg-config file `gio-unix-2.0.pc`.

**Comment by t00** [comment]
Precisely error I am getting on Manjaro - an Arch derivative.

**Comment by mjakeman** [comment]
Odd, it works fine within the flatpak sandbox. It's probably missing the `gio-unix` library although I was under the impression that would be pulled in automatically by `gtk4`.

Does modifiying `src/meson.build` to contain the following work?

```
exm_deps = [
  dependency('glib-unix-2.0'),
  dependency('gtk4'),
  dependency('libadwaita-1'),
  dependency('json-glib-1.0'),
  dependency('libsoup-3.0'),
  dependency('text-engine-0.1')
]
```

**Comment by t00** [comment]
It seems it does not compile:

`../extension-manager-0.3.2/src/meson.build:26:0: ERROR: Dependency "glib-unix-2.0" not found, tried pkgconfig and cmake
`
Necessary headers can be found in the following location:

```
ls /usr/include/gio-unix-2.0/gio/
gdesktopappinfo.h  gfiledescriptorbased.h  gunixfdlist.h  gunixfdmessage.h  gunixinputstream.h  gunixmounts.h  gunixoutputstream.h
```

**Comment by patlefort** [comment]
Adding `gio-unix-2.0` to the dependencies in `src/meson.build` fix the issue. After a little digging, `gtk4.pc` contains `Requires.private: gio-unix-2.0 >=  2.66.0` in the flatpak SDK `org.gnome.Sdk/x86_64/42`.  The one compiled on arch does not. The flatpak one is version 4.6.6 and on arch is 4.8.0. Maybe it's build wrong or something changed in gtk?

**Comment by m911t** [comment]
found this issue thanks to the aur. This exact same error also appears when trying to build g4music from the aur.

**Comment by mjakeman** [comment]
Ah whoops, I meant `gio-unix-2.0` not glib.

Since gtk4's pkgconf file has gio-unix as a private require, we shouldn't be counting on it being included through that. I would consider this a bug.
