### ISSUE TITLE
Delete button is inactive when extensions are disabled

### ISSUE THREAD

**Issue by RocketRide9** [mjakeman/extension-manager#260]
## Problem
Some extensions can crash session. They will be disabled automatically and you can enter your session to repair it. However you can not delete or turn off broken extension while extensions are disabled. Needed buttons are inactive. And you can not enable extensions because session will crash again.

## Tested on
extension-manager 0.3.0

## Screenshots
![Снимок экрана от 2022-09-16 23-12-41](https://user-images.githubusercontent.com/70429241/190684914-e54fabcd-dfb9-43a1-9406-33a453d8eb55.png)
*In gnome-extensions you can not deactivate extension, but you can delete it*

**Comment by mjakeman** [comment]
Ah that's a good point.

This will take a bit of work so it won't make 0.4 but let's schedule this for the next version.
