### ISSUE TITLE
Extension Manager does not support Gradience re-coloring

### ISSUE THREAD

**Issue by martinszeltins** [mjakeman/extension-manager#283]
**UPDATE**: This is a bug with Gradience and Flatpaks. The workaround for now is to run this command:

````
$ sudo flatpak override --filesystem=xdg-config/gtk-4.0
````

I was using Gradience app to do some re-coloring of my libadwaita apps and I found that the one app that was not respecting the colors was the Extension Manager.

I changed the Headerbar to red color but it does not work on Extension Manger.

Screenshot:
![extensmanager](https://user-images.githubusercontent.com/34019878/193309304-f8ea2e34-0d73-445f-b677-0cdef7d80355.jpg)

**Comment by mjakeman** [comment]
Hi, in order to keep Extension Manager simple and maintainable for myself, I don't support any themes other than default libadwaita (although you're more than welcome to theme it yourself!).

Please report this against Gradience. I'm happy to take patches if they improve compatibility :)
