### ISSUE TITLE
Default Upgrade Assistant window size is not wide enough

### ISSUE THREAD

**Issue by rafal06** [mjakeman/extension-manager#296]
Default Upgrade Assistant window size is not wide enough to fit the content, and so the scrollbars appear.

Tested with Extension Manager 0.4.0 Flatpak on Gnome 42.5 and Fedora 35

![image](https://user-images.githubusercontent.com/70489677/194717389-f6bf851f-0009-4137-931b-1ed27c34452d.png)

**Comment by mjakeman** [comment]
Hmm, looks like one or more extension titles are too long to fit in the window. We're probably missing an `ellipsize=true` somewhere.
