### ISSUE TITLE
Sharp corner in the end of "Installed" list

### ISSUE THREAD

**Issue by daudix** [mjakeman/extension-manager#299]
![Снимок экрана от 2022-10-10 18-38-19](https://user-images.githubusercontent.com/77155297/194904029-3a96f24b-b5c5-4263-a233-f87667f8a798.png)
![Снимок экрана от 2022-10-10 18-38-21](https://user-images.githubusercontent.com/77155297/194904035-01eed72d-3446-4a7b-acd0-737c70bbafbe.png)

**Comment by mjakeman** [comment]
Good catch!

I think this is a libadwaita bug to do with placeholders. I've opened https://gitlab.gnome.org/GNOME/libadwaita/-/issues/585.
