### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by Amansour23** [mjakeman/extension-manager#305]
../src/exm-backtrace.c:78 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-comment-dialog.c:139 'on_get_comments'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:80 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'

**Comment by mjakeman** [comment]
Can you provide a description of what you were doing when the error occurred?

Also:
 - Version of extension manager
 - Operating system
 - Method of distribution (flatpak/aur/etc)

**Comment by mjakeman** [comment]
Looks like the same issue as #310
