### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by mjakeman** [mjakeman/extension-manager#31]
In a rather unfortunate turn of events, [extensions.gnome.org](https://extensions.gnome.org/) is down at the moment.

This is a good opportunity to improve error reporting within the program. We should notify the user if:
 - http request fails (i.e. ego could not be reached)
 - dbus command fails (cannot communicate with gnome-shell, invalid state, etc)
 - json parsing fails

It would be good to use libadwaita's new in-app notification widgets to display this.

**Comment by celsotavaresdev** [comment]
I did some tests as an alternative to #198 (trying to install extensions without the `unzip` package), but using GtkWidget:
![Screenshot from 2022-06-10 15-07-02](https://user-images.githubusercontent.com/85074776/173128941-a971566c-0825-4c30-a70f-8557db1b49c5.png)

> It would be good to use libadwaita's new in-app notification widgets to display this.

Hmm, I think it's a good choice. I'll do some research to see how it works too.
