### ISSUE TITLE
Automatic window size height to avoid scrolling

### ISSUE THREAD

**Issue by nekohayo** [mjakeman/extension-manager#317]
Please [autosize](https://fortintam.com/blog/dont-make-me-scroll/) the window to avoid needing me to do it everytime I launch the application. Even better if you could use multiple columns for contents to actually use the widescreen real estate of my display! Ideally, I shouldn't have to scroll at all in most cases.

**Comment by mjakeman** [comment]
The issue with autosizing is under Wayland we don't know the size of the display.

I think not exceeding the display size is more important than scaling to content, but maybe we could have some reasonable bounds for which the app will scale up (e.g. up to 1280x800 or something along those lines).

For multi-column layout, I'm open to the idea but I'm not sure what that would look like.

**Comment by oscfdezdz** [comment]
Is this issue still of interest now that the window can remember its state?
