### ISSUE TITLE
Extension-manager installations (.deb, snap) crashes Ubuntu 22.10 - Gray screen, Log Out option.

### ISSUE THREAD

**Issue by OsniWinkelmann** [mjakeman/extension-manager#319]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.2245" (uid=1000 pid=72617 comm="/snap/gnome-extension-manager/10/usr/bin/extension" label="snap.gnome-extension-manager.gnome-extension-manager (enforce)") interface="org.gnome.Shell.Extensions" member="CheckForUpdates" error name="(unset)" requested_reply="0" destination=":1.2247" (uid=1000 pid=72668 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel" label="unconfined")

I now installed the Flatpak and is working OK.

**Comment by mjakeman** [comment]
> /snap/gnome-extension-manager/

There's no official snap for Extension Manager (WIP support in #314). If you've gotten the app from a third party, please report it to them as there's no way for me to fix it. The official version is the flatpak, so I'm glad that's working for you.

> An AppArmor policy prevents this sender from sending this message to this recipient

It looks to me like the package has been improperly configured - Extension Manager should be working fine within AppArmor's default policies.

Closing as I can't fix on my end

**Comment by OsniWinkelmann** [comment]
Thanks.
