### ISSUE TITLE
Could not check for updates

### ISSUE THREAD

**Issue by plx78** [mjakeman/extension-manager#323]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.91 was not provided by any .service files

**Comment by mjakeman** [comment]
Can you confirm:
 - Operating System
 - Version of Extension Manager
 - Version of GNOME Shell (e.g. 42.4, 43.1, etc)
 - Whether this is the flatpak

Looks to me like the `org.gnome.Shell.Extensions` service isn't running (which we use to manage extensions). That's a bit odd...

**Comment by suhailmahmood** [comment]
I am getting the following error:

> Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Extensions was not provided by any .service files

I am using Linux Mint 21.1 Cinnamon

**Comment by mjakeman** [comment]
> I am using Linux Mint 21.1 Cinnamon

Extension Manager is for GNOME Shell - so it won't work with other desktop environments like Cinnamon.
