### ISSUE TITLE
I con't install any extensions

### ISSUE THREAD

**Issue by YassinOmer** [mjakeman/extension-manager#324]
I tried to install extensions using the browser and clicked on a prompt that showed up nothing happened. I tried using the app same prompt that showed up nothing happened.
On the website there is a message saying :
> Your native host connector does not support the following APIs: v6. Probably you should upgrade the native host connector or install plugins for missing APIs. Refer [documentation](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation) for instructions.

The latest chrome-gnome-shell is installed.
I am using the latest ZorinOS 16.2 it's based on Ubuntu 20.04.
And I tried `sudo apt-get update; sudo apt-get upgrade;`.

![Screenshot from 2022-12-16 00-13-21](https://user-images.githubusercontent.com/76850286/207978862-50d16b0d-e3d5-4e94-a40d-88684c3fb16b.png)
![Screenshot from 2022-12-16 00-15-53](https://user-images.githubusercontent.com/76850286/207978886-74ee50ce-51f3-4891-beec-419d8be5df2b.png)

**Comment by mjakeman** [comment]
The website and the app are unrelated. You don't need the connector plugin `chrome-gnome-shell` for extension manager, so you can safely ignore the warning on the website.

In terms of the popup not doing anything, that will be a problem with gnome shell.

Can you confirm:
 - Your GNOME Shell version (e.g. 42.4, 43.1, etc)
 - The version of extension manager

I have a few ideas what it could be 🤔

**Comment by YassinOmer** [comment]
😅 Sorry wrote your reply late I stopped using Zorn a while a go, now I'm on Fedora everything is working fine here.
