### ISSUE TITLE
Screenshot windows resizer

### ISSUE THREAD

**Issue by avisadius** [mjakeman/extension-manager#326]
Hi
I do turn on active button on extension and try capture screenshot but my lcd become bank, and it worked fine with extensions manager off
![image](https://user-images.githubusercontent.com/44080415/209420110-bae87d96-0b5a-4801-868a-72165ee9698c.png)
when i click on windows mode it going blank

**Comment by avisadius** [comment]
wait, how i can screenshot a screenshot panel

**Comment by mjakeman** [comment]
Sorry, I don't understand the issue...?

Is this a problem with Extension Manager or one of the extensions you have enabled? If you turn them all of individually, can you still reproduce the issue?

If it's a problem with a specific extension, you should report it to the person who made that extension.

**Comment by avisadius** [comment]
i see, thankyou
