### ISSUE TITLE
Extension Manager crashed! (all I did was open the Extension Manager)

### ISSUE THREAD

**Issue by prthorsenjr** [mjakeman/extension-manager#331]
I am running openSUSE Tumbleweed using the Gnome Desktop.

I tried to open the Extension Manager application and got the errors below:

../src/exm-backtrace.c:78 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

I tried uninstalling and reinstalling the application in hopes that it would correct the issue, but it did not.

**Comment by prthorsenjr** [comment]
I forgot to mention that I am running openSUSE Tumbleweed with the Gnome Desktop.

**Comment by prthorsenjr** [comment]
I uninstalled the extension and reinstalled it. That did NOT resolve the issue. It still reports the messages above that prompted the new issue.

**Comment by prthorsenjr** [comment]
As of this afternoon, functionality of the Extension Manager is working as it should. I'm not sure what brought it back to life? I uninstalled Extension Manager via the Gnome Software application (as I had done before). Furthermore, I reinstalled the Extension Manager application from the same Flatpak download I had used before. I rebooted the laptop and it works. Weird.

**Comment by mjakeman** [comment]
Hmm, that's really strange. I've seen a few issues like this, but I have no idea what's causing it. It could be to do with GNOME Extensions infrastructure and some edge cases in error handling.

I think we have other issues covering this, so I'll close this. Feel free to open a new issue if it comes back.
