### ISSUE TITLE
../src/exm-backtrace.c:78 'exm_backtrace_print' ../src/main.c:41 'handler'

### ISSUE THREAD

**Issue by ag-pc** [mjakeman/extension-manager#335]
../src/exm-backtrace.c:78 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

**Comment by mjakeman** [comment]
Seems to be the same as https://github.com/mjakeman/extension-manager/issues/401
