### ISSUE TITLE
Crash when installing an extension

### ISSUE THREAD

**Issue by kdwk** [mjakeman/extension-manager#337]
![Screenshot from 2023-01-29 22-12-45](https://user-images.githubusercontent.com/39268094/215332214-f49d9e34-67be-4ecc-9840-564f1698ffbd.png)

I was told by the app to open an issue here, but I think this doesn't really contain anything important...

**Comment by mjakeman** [comment]
Ah, you're right that's not too helpful 🙃 

Just to see if it's similar to some other issues, can you list:
 - Your Distro
 - Extension Manager Version (e.g. 0.4.0)
 - GNOME Shell Version (e.g. 43.1)
 - Distribution Method (Flatpak, AUR, etc)
 - Are you using Nvidia drivers?
 - Are you using a VPN/Proxy?

**Comment by kdwk** [comment]
I was using carbonOS (carbon.sh). Extension Manager comes with the operating system. I was not using any Nvidia product or a VPN/ proxy. Unfortunately I am back on Fedora Silverblue so I'm unable to answer other questions.

**Comment by mjakeman** [comment]
I'm not sure there's much I can do here without a trace.

I think this is covered by other issues relating to crashes however (where we do have traces).

I'll close this, but if anyone encounters a similar issue on carbonOS feel free to make a new issue.
