### ISSUE TITLE
Improve Appstream data

### ISSUE THREAD

**Issue by mjakeman** [mjakeman/extension-manager#34]
The appstream data (which determines what is displayed on GNOME Software and Flathub) is very barebones at the moment.

For the next update, fill out more fields:
 - Description - Add more detail
 - Developer
 - Release description and changelog
 - Update Contact

**See:** https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

**Comment by oscfdezdz** [comment]
[Translation tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-translation) is also useful for app stores.

Adding `translatable="no"` to the developer_name tag like so `<developer_name translatable="no"></developer_name>` prevents it from being translatable.
