### ISSUE TITLE
Gnome-extensions not working Ubuntu 22.10; Gnome 43.1

### ISSUE THREAD

**Issue by AbhishekOjha08** [mjakeman/extension-manager#341]
I installed and upgraded my ubuntu system but it seems to not support gnome extensions. 
The error I get is: 

Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.120" (uid=1000 pid=46274 comm="/snap/gnome-extension-manager/10/usr/bin/extension" label="snap.gnome-extension-manager.gnome-extension-manager (enforce)") interface="org.gnome.Shell.Extensions" member="CheckForUpdates" error name="(unset)" requested_reply="0" destination=":1.121" (uid=1000 pid=46336 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel" label="unconfined")

**Comment by coderzhaxor** [comment]
hi I also have that problem, but you can try to follow me to solve it. I don't know if this is the best way or not but it works for me.

first when i clicked toggle use extension, i get a pop up that says there's a problem in my gnome shell version. so i decide to search how to fix it, and here you can try to fix it:
you can reinstall gnome shell extension manager with:

```
sudo apt install gnome-shell-extension-manager
```
hope this can help you :)

**Comment by AbhishekOjha08** [comment]
It seems it was a problem with snap package. Using apt fixed it.
Thanks!
