### ISSUE TITLE
Feature Request: Disabling auto-updates and the choice of the extension version

### ISSUE THREAD

**Issue by Opendreas** [mjakeman/extension-manager#346]
When an extension update with critical errors is released, it is impossible to install the previous version, extension manager automatically installs the latest version.
Please add disabling auto-update and selecting the extension version to rollback, if possible.

**Comment by mjakeman** [comment]
Hi, it's not possible to control this on Extension Manager's end. We register ourselves with GNOME Shell and it handles all extension downloads/updating/etc. Whenever the user logs in, Shell will automatically check for updates.

I would suggest opening an issue on the [gnome-shell repo](https://gitlab.gnome.org/GNOME/gnome-shell/) as the solution likely involves pinning extensions at a given version.

One workaround is to manually download the working extension and give it a larger version than the currently released one by editing its metadata.

**Comment by Anvil5465** [comment]
To anyone interested, there is a relevant issue open on the gnome shell repo here: [GNOME/gnome-shell#2514](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2514) and open MR here: [GNOME/gnome-shell!3053](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3053)
