### ISSUE TITLE
gnome extension not working.

### ISSUE THREAD

**Issue by anupam2150** [mjakeman/extension-manager#348]
Compiz alike magic lamp effect not working

**Comment by anupam2150** [comment]
> Compiz alike magic lamp effect not working

**Comment by anupam2150** [comment]
Compiz alike magic lamp effect not working

**Comment by mjakeman** [comment]
Hi, this bug tracker is only for problems with Extension Manager.

Please report your issue to the creator of the extension that isn't working.
