### ISSUE TITLE
extension manager not working!!!!!!

### ISSUE THREAD

**Issue by drfthu** [mjakeman/extension-manager#349]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.169" (uid=1000 pid=11565 comm="/snap/gnome-extension-manager/10/usr/bin/extension" label="snap.gnome-extension-manager.gnome-extension-manager (enforce)") interface="org.gnome.Shell.Extensions" member="CheckForUpdates" error name="(unset)" requested_reply="0" destination=":1.170" (uid=1000 pid=11600 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel" label="unconfined")

**Comment by mjakeman** [comment]
The snap package (which is currently unofficial) is known to be broken.

Please use the [official flatpak](https://flathub.org/apps/details/com.mattjakeman.ExtensionManager) package as that has been tested and works on Ubuntu.
