### ISSUE TITLE
the extension's url has an extra / in it.

### ISSUE THREAD

**Issue by artistic-hacktivist** [mjakeman/extension-manager#351]
example: the actual url of an extension might be https://extensions.gnome.org/extension/3433/fly-pie/ but when you click "view on extensions" it sends you to the wrong url: https://extensions.gnome.org//extension/3433/fly-pie/

as you can see the url has an extra / in it.
this happens with all extensions not just this one

this is probably the result of a typo

**Comment by oscfdezdz** [comment]
Is this still an issue? I can't reproduce it.

**Comment by oscfdezdz** [comment]
This was fixed by #210
