### ISSUE TITLE
Failure on installing Simple Message

### ISSUE THREAD

**Issue by ThePixelMixery** [mjakeman/extension-manager#352]
../src/exm-backtrace.c:78 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
../src/local/exm-manager.c:323 'list_model_contains'
../src/local/exm-manager.c:345 'exm_manager_is_installed_uuid'
../src/exm-detail-view.c:421 'exm_detail_view_update'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/local/exm-manager.c:755 'on_state_changed'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/local/shell-dbus-interface.c:2756 'shell_extensions_proxy_g_signal'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'

**Comment by mjakeman** [comment]
Let's track this in #406
