### ISSUE TITLE
"AutoSearch on key-press" or "Ctrl + /"

### ISSUE THREAD

**Issue by genefyx** [mjakeman/extension-manager#355]
While using the extensions I'm attempting to use the in app search and I currently have to CTRL + Tab before I can begin searching or click in the search area.

Could we add a search on key-press similar to standard gnome applications.
If not then a "CTRL + /"?

**Comment by mjakeman** [comment]
I agree. Let's do type-to-search like other GNOME apps.

I'll schedule this as part of the 1.0 version refresh
