### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Espiritus-le-ujo** [mjakeman/extension-manager#358]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.167" (uid=1000 pid=7032 comm="/snap/gnome-extension-manager/10/usr/bin/extension" label="snap.gnome-extension-manager.gnome-extension-manager (enforce)") interface="org.gnome.Shell.Extensions" member="CheckForUpdates" error name="(unset)" requested_reply="0" destination=":1.168" (uid=1000 pid=7068 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel" label="unconfined")

**Comment by mjakeman** [comment]
Hi, this should be fixed in the latest snap package - you'll need classic confinement for this to work
