### ISSUE TITLE
in my extension manager app all extensions are unsupported. please fix it. 

### ISSUE THREAD

**Issue by RaoMuhammadUmar216** [mjakeman/extension-manager#362]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.175" (uid=1000 pid=9597 comm="/snap/gnome-extension-manager/10/usr/bin/extension" label="snap.gnome-extension-manager.gnome-extension-manager (enforce)") interface="org.gnome.Shell.Extensions" member="CheckForUpdates" error name="(unset)" requested_reply="0" destination=":1.176" (uid=1000 pid=9629 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel" label="unconfined")

**Comment by mjakeman** [comment]
Hi this should be fixed in the latest snap package - you'll need "classic" confinement for it to work
