### ISSUE TITLE
All Extensions Listed as Unsupported.

### ISSUE THREAD

**Issue by cellarpress** [mjakeman/extension-manager#366]
Attempting to reinstall Extensions on Ubuntu 22.04
All extensions come bieged out and say Unsupported.

![Screenshot from 2023-04-01 23-41-43](https://user-images.githubusercontent.com/112870447/229323287-663c3369-dc18-4b32-8a72-feac2a7eeee2.png)

**Comment by mjakeman** [comment]
Is this still an issue?

**Comment by cellarpress** [comment]
All sorted. Thanks.

**Comment by geoffbrowne** [comment]
Would be helpful to just let us know how you fixed it please ?
I have same problem.

**Comment by cellarpress** [comment]
IIRC uninstalled and installed using the flatpak version.

**Comment by mjakeman** [comment]
Hey @geoffbrowne, which package version and format are you using?
