### ISSUE TITLE
Could not check for updates: GDBus.

### ISSUE THREAD

**Issue by bcaregnani** [mjakeman/extension-manager#367]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.8934" (uid=1000 pid=225099 comm="/snap/gnome-extension-manager/10/usr/bin/extension" label="snap.gnome-extension-manager.gnome-extension-manager (enforce)") interface="org.gnome.Shell.Extensions" member="CheckForUpdates" error name="(unset)" requested_reply="0" destination=":1.8935" (uid=1000 pid=225121 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel" label="unconfined")

**Comment by mjakeman** [comment]
Should be fixed by the latest snap package version - please update
