### ISSUE TITLE
Doesn't install fully extension

### ISSUE THREAD

**Issue by shm0rt** [mjakeman/extension-manager#375]
can't install fully an extension. After running the application on another gpu (Nvidia RTX 3050ti) all the application does is installing the file into my .local/share/gnome-shell/extensions but not the content.

**Comment by mjakeman** [comment]
Can you provide:
 - Operating System (e.g. Ubuntu)
 - App Version (e.g. 0.4.0)
 - Package Format (Flatpak?)

**Comment by shm0rt** [comment]
It was: 
Fedora 38
App Version 0.4
Flatpak (Flathub)

**Comment by shm0rt** [comment]
I don't know where exactly the problem is, but i have found out that if you try to take the installed gnome-extensions and copy them onto new system this bug comes out.
My Solution was to reinstall OS. I wanted to switch the OS anyway to Ubuntu...

It would be nice if you would add a new function:
It should make possible to save all extensions as a file and if i would need them on a new system, i could just import it.
If it would need to install the extensions again, it's ok but the program should do that for the user automatically, instead of searching every single extension manually and downloading it.

Though thanks for the respond:)

**Comment by mjakeman** [comment]
Ah, yeah I'm not sure that's anything we can fix on this end.

It'll be related to how GNOME Shell handles extensions, so I'll close this.

For transferring extensions, see #75
