### ISSUE TITLE
Extension Manager crashes whenever the page for an extension is opened

### ISSUE THREAD

**Issue by Iron-Squid** [mjakeman/extension-manager#377]
OS: Arch Linux (fully updated)

Expected behavior: I click on an extension to view the page/reviews, and I'm able to scroll through the page+look at the contents with no issue

Actual behavior: I click on an extension to view the page/reviews, and I'm able to view the page for less than a second before it crashes.

Debug output from Terminal:
```
(extension-manager:8970): GLib-GObject-CRITICAL **: 17:01:34.002: g_object_set_is_valid_property: object class 'TextDisplay' has no property named 'frame'
A fatal error has occurred.
Please report this to 'https://github.com/mjakeman/extension-manager' and attach the following crash report:

START BACKTRACE

(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

END BACKTRACE
```

**Comment by mjakeman** [comment]
> (extension-manager:8970): GLib-GObject-CRITICAL **: 17:01:34.002: g_object_set_is_valid_property: object class 'TextDisplay' has no property named 'frame'

Ah, this doesn't look good.

I have no idea how that's happening actually.

Is this still an issue now? Are you using the flatpak or some other package?

**Comment by Iron-Squid** [comment]
> > (extension-manager:8970): GLib-GObject-CRITICAL **: 17:01:34.002: g_object_set_is_valid_property: object class 'TextDisplay' has no property named 'frame'
> 
> Ah, this doesn't look good.
> 
> I have no idea how that's happening actually.
> 
> Is this still an issue now? Are you using the flatpak or some other package?

Pardon the late reply, and the accidental closing/reopening.

I'm not using the flatpak, I'm using the version that comes from the AUR. It's been an issue for as long as I remember.

**Comment by Iron-Squid** [comment]
Sorry again.

**Comment by Iron-Squid** [comment]
Update on this bug. 

I've since reinstalled my entire system due to multiple errors piling up on account of my inexperience with Arch.
The app now works properly, and does not crash.
