### ISSUE TITLE
Upon installing an extension that has a configuration / settings panel, reveal that button the installation page / extension profile

### ISSUE THREAD

**Issue by nekohayo** [mjakeman/extension-manager#380]
Many/most extensions need configuration after installation, but that may not be clear to the user, particularly when the UI looks like this:

![image](https://user-images.githubusercontent.com/479401/234085719-c5e22ffc-a6ed-4016-b358-1db57dbb5901.png)

On the left (?) of the "Installed" button (which should be replaced by a "Remove" button, issue #379), it should show a "Configure" button, both as a convenient shortcut, but also as a clear visual indication that the newly installed extension actually allows (or requires) configuration.

**Comment by mjakeman** [comment]
Let's track this under https://github.com/mjakeman/extension-manager/issues/197
