### ISSUE TITLE
Doesn't properly install extensions without "schemas" dir

### ISSUE THREAD

**Issue by JamiKettunen** [mjakeman/extension-manager#381]
Attempting to install https://extensions.gnome.org/extension/5410/grand-theft-focus/ for example results in:
```
** (extension-manager:3): CRITICAL **: 12:06:44.490: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:org.gnome.Shell.ExtensionError: Error when getting information for file “/home/user/.local/share/gnome-shell/extensions/grand-theft-focus@zalckos.github.com/schemas”: No such file or directory
```
With the extension not appearing on the installed list and providing the button to install again (which results in the same problem):
![image](https://user-images.githubusercontent.com/47358222/234271528-8e289fd8-8ec9-4fe0-9a8d-6baed23a4bc9.png)

Restarting the app doesn't change anything about the extension status either despite `extension.js` and `metadata.json` files existing under `/home/user/.local/share/gnome-shell/extensions/grand-theft-focus@zalckos.github.com/`.

Logging out and back in shows the extension as installed and enabled however:
![image](https://user-images.githubusercontent.com/47358222/234272395-6f18e125-08cc-4cef-a23d-6089da887af1.png)

I'm using the v0.4.0 flatpak (under [Chimera Linux](https://chimera-linux.org/) fwiw)

**Comment by uricot** [comment]
Same issue for me on nixos unstable

**Comment by mjakeman** [comment]
Is this still an issue? And is it only for `grand-theft-focus`?

**Comment by oscfdezdz** [comment]
I have been trying to reproduce the bug over the last few months as new versions of GNOME have been released without success. Please open a new issue if, as mentioned above, it is still a problem.
