### ISSUE TITLE
Version string not updated in v0.4.1

### ISSUE THREAD

**Issue by foo-dogsquared** [mjakeman/extension-manager#386]
The version string still says 0.4.0 in the "About" dialog.

![image](https://user-images.githubusercontent.com/34962634/236605967-deb29195-f86f-4086-ace6-fbdd8b31e4a0.png)

(The application was built from source with nixpkgs.)

**Comment by mjakeman** [comment]
Oh nice catch!

Looking at the code, I somehow tagged the release without merging the release notes 🙃

I think to avoid any problems, I'll make a new v0.4.2 tagged release with the currently active PRs and proper release notes.

**Comment by ViBE-HU** [comment]
I'm on Ubuntu 20.04 and using the Flatpak version bun not just the version number same but even if I reinstall it I still get the recent release. Is my issue related?
