### ISSUE TITLE
gjs and unzip being sourced from system rather than flatpak

### ISSUE THREAD

**Issue by najepaliya** [mjakeman/extension-manager#391]
GJS and unzip, both of which are required for the GUI to function as expected, are sourced from the system rather than the org.gnome.Platform runtime. 

I double-checked to make sure that org.gnome.Platform 44 has both gjs and unzip.

**Comment by mjakeman** [comment]
IIRC, this is because GJS and unzip are dependencies of GNOME Shell itself.

This probably means the GNOME Shell package doesn't include the relevant dependencies for DBus to work.

What distro are you using?

**Comment by najepaliya** [comment]
On Debian, gjs and unzip are actually recommended packages. If you have apt set up not to pull in recommended, i.e. only install required packages, it leads to a silent failure/error. Not a huge issue, but if possible it would be nice to source from the sandboxed runtime rather than the system. 

https://packages.debian.org/sid/gnome-shell

**Comment by mjakeman** [comment]
Doesn't seem like this is something we can fix on our end - GNOME Shell handles all extension installation and management now, so we have no way to inject our own unzip and gjs (and probably shouldn't be allowed to, all things considered)
