### ISSUE TITLE
Could not check for updates: GDBus.Error

### ISSUE THREAD

**Issue by mainDevgithub** [mjakeman/extension-manager#393]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Extensions was not provided by any .service files

**Comment by Omcsesz** [comment]
+1, the same for me

**Comment by sonzr** [comment]
Me too

**Comment by mjakeman** [comment]
Hmm

Could you provide more information about your OS, Version (of extension manager e.g. 0.4.0), and package format (Flatpak?)

**Comment by mjakeman** [comment]
Please feel free to open a new issue if this is still occurring with the information requested above
