### ISSUE TITLE
Save installed Extensions

### ISSUE THREAD

**Issue by Schildkroet** [mjakeman/extension-manager#395]
Hello,
would it be possible to add a "save"-feature, which saves all installed extensions in a file so you can use this file to install extensions on another pc just by loading the file. 

This would make it much easier to setup a new pc.

**Comment by kindaran** [comment]
That would certainly make things simpler. I've been using: 

`cp -ru ~/.local/share/gnome-shell/extensions/ /path/to/save/to/`

**Comment by mjakeman** [comment]
See #75, I think that's effectively the same thing?
