### ISSUE TITLE
Serious race condition in search callback

### ISSUE THREAD

**Issue by Arcitec** [mjakeman/extension-manager#397]
There's a serious race condition in the Browse/Search panel:

- If the user types, Extension Manager begins a search.
- If the user finishes typing BEFORE Extension Manager has finished the OLD search, then the app breaks and won't show any results.

Here's how you can reproduce this bug:

- Press `Ctrl + A` to select all text in the search field.
- Type `pano` as fast as you can.
- Repeat the previous steps until you cannot see "pano" in the search results anymore. That means you've triggered the race condition (where it doesn't update the search results with your final search text).
- Remove one letter: `pano -> pan`, wait for Extension Manager's search to finish, and then re-add the last letter: `pan -> pano`. Now it will appear.

This issue means that people can't find certain extensions, such as Pano, if they're fast at typing.

The solution would be to code something that runs a final search "around 0.5 seconds after" the user has stopped typing, if the last-executed automatic search wasn't for that exact term. Just to ensure that the final search always has their exact terms. Perhaps only if the search term itself is short and likely to bring up a lot of other results (for example, in the demo here, I suspect that the issue is that the intermediary search for `pa` or `pan` is what's bringing up all the junk instead of finding `pano`, and since Ext Manager never does a final search for `pano`, it doesn't find that extension).

**Comment by mjakeman** [comment]
Thanks for looking into this!

I was aware of a race condition, but haven't had the time to figure out what's causing it. We should debounce search (add a delay) and cancel the previous search operation when launching a new one.

**Comment by mjakeman** [comment]
This is hopefully now fixed.

I've resolved this by:
 * Dispatching a GCancellable with each request
 * Storing the most recent cancellable in the search provider
 * Cancelling the most recent operation whenever we start a new one

Therefore there should only ever be one active 'uncancelled' operation.

We should still probably debounce the search though, if only to put less load on the GNOME servers
