### ISSUE TITLE
Crash in refresh_search

### ISSUE THREAD

**Issue by Nilabh567** [mjakeman/extension-manager#398]
../src/exm-backtrace.c:78 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-browse-page.c:162 'refresh_search'
../src/exm-browse-page.c:198 'on_first_page_result'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:76 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'

**Comment by GOLI001** [comment]
../src/exm-backtrace.c:78 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-browse-page.c:162 'refresh_search'
../src/exm-browse-page.c:198 'on_first_page_result'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:76 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'

i also have this error

**Comment by mjakeman** [comment]
I believe this is now fixed
