### ISSUE TITLE
No indicator that all extensions are disabled in GNOME Extensions

### ISSUE THREAD

**Issue by bobbysbytes** [mjakeman/extension-manager#40]
Might be a uncommon bug, but if you have your extensions disabled via GNOME Extensions, Extension Manager will still mark extensions as being turned on. Allowing extensions in GNOME Extensions restores functionality to the application. 

Perhaps there could be an indicator if a user has both application installed that extensions have been disabled?

**Comment by mjakeman** [comment]
Way ahead of you :)

Support for globally turning on/off extensions was added in #39. If extensions are off, the list view is marked insensitive.
