### ISSUE TITLE
Crash in run_app (on Manjaro, others)

### ISSUE THREAD

**Issue by hungryLa** [mjakeman/extension-manager#401]
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

**Comment by mjakeman** [comment]
Hi,

does this happen regularly (every time you open the app) or only now and then?

That error log doesn't contain anything that will help me narrow down the issue unfortunately.

Also, are you using Flatpak or something else?

**Comment by mjakeman** [comment]
Please feel free to open a new issue with these details.

Specifically, please mention whether this package was installed using snap as this is a known issue (#424).
