### ISSUE TITLE
Extension Manager in KDE PLasma 

### ISSUE THREAD

**Issue by snakeoilaficionadp** [mjakeman/extension-manager#405]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.556 was not provided by any .service files

**Comment by mjakeman** [comment]
Hi, Extension Manager uses GNOME Shell over DBus to manage extensions, so it needs to be run under a GNOME session.

Unfortunately there's no technical way to make it work from a different DE.
