### ISSUE TITLE
[Feature Request] Add Donation feature

### ISSUE THREAD

**Issue by alexsch01** [mjakeman/extension-manager#407]
https://www.reddit.com/r/linux/comments/144zxil/gnome_extensions_now_supports_donation/

**Comment by oscfdezdz** [comment]
Donation links can now be added. Like extension's homepage, they weren't available. See https://gitlab.gnome.org/Infrastructure/extensions-web/-/commit/f6a54963c4f8fc1a48c9e002eb29f138eb7ad983

I was thinking of using `AdwExpanderRow` or `AdwComboRow` as there can be up to 7 donation links (not sure if the custom field can be more than one) and adding an `AdwActionRow` for each would be too much.
