### ISSUE TITLE
Extension Manager crashing & giving error on Ubuntu 22.0.4.2

### ISSUE THREAD

**Issue by abranasays** [mjakeman/extension-manager#412]
### Error Output Below:

```
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-window.c:437 'exm_window_init'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-application.c:61 'get_current_window'
../src/src/exm-application.c:91 'exm_application_activate'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
```

**Comment by feer9** [comment]
Similar crash here

`../src/exm-backtrace.c:78 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-installed-page.c:211 'show_updates_bar'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'
`

**Comment by mjakeman** [comment]
Could you also provide:
 - Extension Manager version (e.g. 0.4.0)
 - Package format (Flatpak, snap, something else)

I've had a lot of Ubuntu-related crash reports recently, which is a bit concerning 🤔

**Comment by mjakeman** [comment]
Feel free to open a new issue with the above information
