### ISSUE TITLE
Extension Manager Error in linux Mint

### ISSUE THREAD

**Issue by adibro-213** [mjakeman/extension-manager#413]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.820 was not provided by any .service files

**Comment by mjakeman** [comment]
Could you provide:
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.4.0)
 - Package format (Flatpak, snap, something else)

**Comment by mjakeman** [comment]
Feel free to open a new issue with the above information
