### ISSUE TITLE
GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod

### ISSUE THREAD

**Issue by willianmendesf** [mjakeman/extension-manager#415]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Nenhuma interface “org.gnome.Shell.Extensions” no objeto no caminho /org/gnome/Shell

**Comment by mjakeman** [comment]
Could you provide:
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.4.0)
 - Package format (Flatpak, snap, something else)

**Comment by mjakeman** [comment]
Feel free to open a new issue with the above information
