### ISSUE TITLE
gnome-extension-manager

### ISSUE THREAD

**Issue by abbadsa** [mjakeman/extension-manager#417]
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-window.c:437 'exm_window_init'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-application.c:61 'get_current_window'
../src/src/exm-application.c:91 'exm_application_activate'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

**Comment by mrtdeh** [comment]
i will get this error too

ubuntu 20

**Comment by mjakeman** [comment]
Could you provide:
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.4.0)
 - Package format (Flatpak, snap, something else)
