### ISSUE TITLE
Extension Manager can't open

### ISSUE THREAD

**Issue by amalroy378** [mjakeman/extension-manager#422]
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-window.c:437 'exm_window_init'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-application.c:61 'get_current_window'
../src/src/exm-application.c:91 'exm_application_activate'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

This error occurs after installation

**Comment by mjakeman** [comment]
Could you provide:
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.4.0)
 - Package format (Flatpak, snap, something else)

**Comment by amalroy378** [comment]
Distro :  Ubuntu 22.04
Extension Manager Version: 0.4.0
Package Format : Snap
