### ISSUE TITLE
Snap package crashes on startup

### ISSUE THREAD

**Issue by ffresco** [mjakeman/extension-manager#424]
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-application.c:61 'get_current_window'
../src/src/exm-application.c:91 'exm_application_activate'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

**Comment by mrpbennett** [comment]
+1

**Comment by mmkinawi** [comment]
same here as well!

**Comment by paul9115** [comment]
I did manage to get it to open after a few attempts from the CLI, but got the following output when it failed 
![image](https://github.com/mjakeman/extension-manager/assets/32612194/8a108bc4-4700-4d9f-8526-28d79dce3100)

**Comment by mjakeman** [comment]
This line is a bit odd, definitely shouldn't be happening:
```
undefined symbol: gtk_widget_dispose_template
```

I would appreciate if someone could answer the following:
 - Did this happen with other versions of Ubuntu or just 23.10?
 - Do other libadwaita apps work fine?
 - Does this occur with the flatpak package, the snap package, or both?

I'll try spin up an Ubuntu VM and test this in the next few days

**Comment by paul9115** [comment]
> This line is a bit odd, definitely shouldn't be happening:
> ```
> undefined symbol: gtk_widget_dispose_template
> ```
> 
> I would appreciate if someone could answer the following:
>  - Did this happen with other versions of Ubuntu or just 23.10?
I think looking through the bug reports and through my own experiences (the error I posted was from a fedora 38 box)
I have an arch install as well so can test that later on. 
>  - Do other libadwaita apps work fine?
I've not noticed anything specially, but I've not spent a whole lot of time looking either, I'll see if I have any other libadwaita apps installed and see if they fail. 
>  - Does this occur with the flatpak package, the snap package, or both?
The error log I posted was from the snap package, I'll uninstall it and install the flatpack package to see if I can reproduce the issue

**Comment by mjakeman** [comment]
Just a general question: Is everyone on this thread using the snap package?

I'm getting quite a few reports of crashing on Ubuntu, and snap seems to be the common factor 🤔

**Comment by mjakeman** [comment]
Hi all,

As per https://github.com/mjakeman/extension-manager/issues/117#issuecomment-1636901291 I don't think it's feasible to continue to support the Snap package.

I would recommend, as alternatives:
 * Installing via [flatpak](https://flathub.org/apps/details/com.mattjakeman.ExtensionManager)
 * Installing via Canonical's [.deb package](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=gnome-shell-extension-manager&searchon=names)

These have been tested to work on Ubuntu and will give a much better experience
