### ISSUE TITLE
Broken search results

### ISSUE THREAD

**Issue by thatLeaflet** [mjakeman/extension-manager#431]
**Describe the bug**
Search is not bringing up extensions even with exact names. Additionally, unsupported extensions are being shown despite the option being disabled.

**System Information:**
 - Fedora Silverblue
 - Extension Manager version 0.4.2
 - Flatpak

**Additional context**
![Screenshot from 2023-06-27 23-11-13](https://github.com/mjakeman/extension-manager/assets/80165419/e40125a9-cfe0-47d1-8268-83cc03a3b58b)
![Screenshot from 2023-06-27 23-12-02](https://github.com/mjakeman/extension-manager/assets/80165419/bfdae4e1-3e89-4781-a179-45b47c07d446)

**Comment by Vsrq** [comment]
Can confirm. Running Fedora 38 Workstation.

Thought I screwed something up with my install or if it had any relations with the OSTree flatpak bug.

**Comment by nomadfh** [comment]
I'm noticing this too. Sometimes I have to spell the entire word to find the search (in the case of caffeine), while in other cases it'll just randomly show up about a third of the way in (alphabetical app grid).

**Comment by gurgelio** [comment]
I'm using flatpak extension manager 0.4.2 on debian 12.
Search is broken here too

**Comment by adamRHargreaves** [comment]
Confirmed seeing this on PopOS 22.04 too.  installed from flatpak (v0.3.0 apparently)

**Comment by ArtikusHG** [comment]
This is not a bug with the application, but rather a bug with the GNOME extension store. As you can see, trying to search for an extension there gives the same kind of broken results:

![image](https://github.com/mjakeman/extension-manager/assets/24320212/08473bf8-efeb-423d-99dc-49a5c2968923)

The solution that worked for me, as of right now, is to sort by downloads. This seems to be the only sort option that brings up relatively relevant results. For now, we should use this, wait and report the bug directly to GNOME unless they fix it themselves.

**Comment by mjakeman** [comment]
Thanks @ArtikusHG for investigating.

It could also be related to #397, but it's much more likely this is a bug with the extensions website.

**Comment by mjakeman** [comment]
Fixed upstream 🎉 

See: https://gitlab.gnome.org/Infrastructure/extensions-web/-/issues/257
