### ISSUE TITLE
Fetching "Recent" not work

### ISSUE THREAD

**Issue by LeeRoyManea** [mjakeman/extension-manager#441]
**Describe the bug**
Fetching "Recent" not work in Search Tab.  
No results. I have the Issue in 2 fedora devices. 
Rest works fine  

**System Information:**
 - Distro Fedora
 - Extension Manager version .0.4.2
 - Package format  Flat

**Comment by mjakeman** [comment]
Do the other three search options work? e.g. Popularity, etc

There have been some changes upstream, so maybe this has broken something 🤔

**Comment by LeeRoyManea** [comment]
The rest of the app works. Just recent does not work.

**Comment by LeeRoyManea** [comment]
In the fedora notebook (latest updates) this feature also not works. When you add some Text to the search you geht results.
