### ISSUE TITLE
"Use Extensions" switches itself off.

### ISSUE THREAD

**Issue by ChrisOfBristol** [mjakeman/extension-manager#443]
I use Applications Menu and Hot Edge, the latter adds the only thing missing from Fedora. Unfortunately it often stops working - when I check Extension Manager, Use Extension is switched off.

Fedora v38
Extension Manager "About" states that it's  v0.4.0, but not whether it is a Flatpak or something else.

**Comment by mjakeman** [comment]
Do you mean that sometimes extensions randomly become disabled?

I've experienced this too on Fedora, but I can't recall whether it happens just with Extension Manager or the GNOME Extensions app too.

To check if the app is flatpak, could you run:

```
$ flatpak list
```

and see if `com.mattjakeman.ExtensionManager` appears?

**Comment by ChrisOfBristol** [comment]
"Do you mean" Yes.
"I've experienced this too" I'm only using Extension Manager, I don't recall trying Gnome Extensions."
"To check" It's a Flatpak.

**Comment by ChrisOfBristol** [comment]
I've removed Extension-Manager and installed Gnome-Extensions, that might narrow it down.

**Comment by mjakeman** [comment]
I'm convinced this has been fixed by GNOME Shell

I used to see it every now and then, but haven't had it in a while since upgrading to Fedora 39.

Fingers crossed it's fixed for good 🤞
