### ISSUE TITLE
Gnome Extensions Manager crashes

### ISSUE THREAD

**Issue by dabartmess** [mjakeman/extension-manager#445]
**Describe the bug**
Opened the manager, tried to turn on extensions, and it died.

**System Information:**
 - Distro Ubuntu 23.04
 - Extension Manager version 0.4.0
 - Package format Ubuntu

**Additional context**
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-window.c:437 'exm_window_init'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-application.c:61 'get_current_window'
../src/src/exm-application.c:91 'exm_application_activate'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

**Comment by 2bndy5** [comment]
+1 to this.. I just hit the same exact problem.

**Comment by eshafferpdx** [comment]
Same issue, please consider merge of #446 with this ticket.

**Comment by eshafferpdx** [comment]
Copied and pasted from #446 

System Information:
-Ubuntu 23.04

Extension Manager version - app force closes when accessing 'About Extension Manager' menu selection, version unknown via App. Gnome Software Center shows 0.40 version
Package format - Snap
Additional context
While Extension Manager crashes with the error above, it will successfully launch after opening Extensions app, v44.2, .deb.

**Comment by 2bndy5** [comment]
I'm not booted into Ubuntu (22.04) right now, but I installed it from the Ubuntu software store (snap I think). It crashes on launch for me though; I don't even get a window, just the error message saying to file the issue.

**Comment by dabartmess** [comment]
> > Extension Manager version (e.g. 0.4.2)
> > Package format (Flatpak, Snap, other)
> 
> Please provide your system information
> 
> I suspect this is related to #424

Updated.. Had a hard time finding the EM version...

**Comment by 2bndy5** [comment]
Thanks quick response!
