### ISSUE TITLE
extension-manager does not show any extensions installed, but extensions are enabled and running fine

### ISSUE THREAD

**Issue by JulesRoland** [mjakeman/extension-manager#449]
Issue occurs on Debian 12 Stable, I'm not sure why, all extensions are working, it's only extension-manager that fails to display extensions or browse for new ones, error message displayed:

Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.330 was not provided by any .service files

**Comment by JulesRoland** [comment]
Removed the extension named "Blur my Shell" and Extension-Manager started working again!

**Comment by mjakeman** [comment]
Great to hear - it's possible GNOME Shell ended up in a bad state and removing the extension reset something.

Feel free to open a new issue if this comes up again.
