### ISSUE TITLE
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.177 was not provided by any .service files

### ISSUE THREAD

**Issue by revocoder0** [mjakeman/extension-manager#452]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.177 was not provided by any .serv
![tocmi](https://github.com/mjakeman/extension-manager/assets/74349878/d7abb6b9-4c6d-4aad-ac63-53271eb88a60)
ice files

And unsupported GNOME.

![tocommit](https://github.com/mjakeman/extension-manager/assets/74349878/ed3a10be-d15b-467e-b120-3608bb95baba)

**Comment by oscfdezdz** [comment]
Hi,

From your screenshots, I assumed it's Kali Linux and I have set up a VM to test it and it works as expected with GNOME Shell. Kali's installer defaults to XFCE desktop environment. Can you confirm that you are using GNOME and which version? A quick way to do this is to run `echo $XDG_CURRENT_DESKTOP` command in a terminal.

**Comment by oscfdezdz** [comment]
Closing as I've seen this error pop up on systems without GNOME installed. Also, in the first screenshot, modal dialogs aren't treated as GNOME does.
