### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by Souvik-Code** [mjakeman/extension-manager#453]
**Describe the bug**

Support Log
----
Version: 0.4.2
Development: No
Package Format: Unknown Package
Status: Official
----
../src/exm-backtrace.c:79 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-comment-dialog.c:139 'on_get_comments'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:80 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'

**System Information:**

 - Distro : Debian 
 - Extension Manager version : 0.4.2
 - Package format : Flatpak

**Comment by oscfdezdz** [comment]
Looks like a duplicate of #400

**Comment by mjakeman** [comment]
Duplicate of #495
