### ISSUE TITLE
App does not launcher on Fedora 38 (Gnome 44)

### ISSUE THREAD

**Issue by H34TW4V3** [mjakeman/extension-manager#467]
This is the error message 

../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-window.c:437 'exm_window_init'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-application.c:61 'get_current_window'
../src/src/exm-application.c:91 'exm_application_activate'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

**System Information:**
 - Distro = Fedora
 - Extension Manager version (latest available - Downloaded yesterday)
 - Package format (flatpak, snap, appimage, rpm)

**Comment by mjakeman** [comment]
Let's track this in #644 

It's not exactly the same, but I think it'll also be related to the GTK environment (hence why it crashed when creating a window)
