### ISSUE TITLE
Search problems

### ISSUE THREAD

**Issue by vinaooo** [mjakeman/extension-manager#470]
Search only works when I write an word completely
if I write it partialy the search not works

like "Rounde" and "Rounded"

images:

![Captura de tela de 2023-08-23 20-17-41](https://github.com/mjakeman/extension-manager/assets/2487145/ab5d1a2e-9e1b-4b74-ace5-d9097a2d083c)
![Captura de tela de 2023-08-23 20-17-54](https://github.com/mjakeman/extension-manager/assets/2487145/fa4f45e8-fde0-49a0-a5d9-995357f203c2)

System Information:
 - Distro (Ubuntu 23.04)
 - Extension Manager version 0.4.2
 - Package format Flatpak

**Comment by oscfdezdz** [comment]
It seems it was a bug in the extensions web, here it works correctly again.

![image](https://github.com/mjakeman/extension-manager/assets/42654671/72ef4314-265c-47f6-bde9-bb04848f2a59)

**Comment by mjakeman** [comment]
This should be fixed in 0.4.3 - feel free to re-open if not the case 🙂
