### ISSUE TITLE
An unexpected error occurred in Extension Manage while opening it

### ISSUE THREAD

**Issue by byStrange** [mjakeman/extension-manager#471]
**Describe the bug**
After upgrading to ubuntu 23.04 I can't install any Gnome extension, now I can't even and use the app itself. Every time when I open it, it crashes

**System Information:**
 - Distro - Ubuntu
 - Extension Manager version (44.3)

**Additional context**
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

**Comment by mjakeman** [comment]
Let's track it in #644
