### ISSUE TITLE
Special characters prevent Extension name from appearing?

### ISSUE THREAD

**Issue by Batwam** [mjakeman/extension-manager#473]
Hi,

Apologies if this is a know issue. I have installed the amazing [mpris-label extension](https://extensions.gnome.org/extension/4928/mpris-label/) which is now called "Media Label & Controls (Mpris Label)". I don't know if a known bug but I noticed that the extension name no longer appears in [Extension Manager:](https://flathub.org/apps/com.mattjakeman.ExtensionManager)
![image](https://github.com/Moon-0xff/gnome-mpris-label/assets/56710655/937858e2-8efa-4a8f-8517-fb92cb9ed284)

I removed the `&` from the name in metadata.json and the name came back. 
![image](https://github.com/Moon-0xff/gnome-mpris-label/assets/56710655/afed306d-5c70-4780-824c-ca6ff3fdfbe6)

Note that the issue doesn't appear in [Extensions](https://flathub.org/apps/org.gnome.Extensions):
![image](https://github.com/Moon-0xff/gnome-mpris-label/assets/56710655/4556b9d4-cea8-46ec-9659-0354824a2e14)

**System Information:**
 - Distro Ubuntu 23.10
 - Extension Manager version 0.4.0
 - Package format: deb - universe repo lunar lobster

**Comment by Batwam** [comment]
For info, I just tried 0.4.2 as flatpak and the same issue occurs

**Comment by Moon-0xff** [comment]
It looks like this was an old bug (#179, #173) fixed on #175, but reverted on 719e888a71ec53498cc15cbe80619b6d2b2a46c0 (#278).
