### ISSUE TITLE
Help Me, Im Using deepin linux os

### ISSUE THREAD

**Issue by AnwaArtCode** [mjakeman/extension-manager#474]
Support Log
----
Version: 0.4.2
Development: No
Package Format: Unknown Package
Status: Official
----
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Extensions was not provided by any .service files

**Comment by oscfdezdz** [comment]
Hi,

Deepin Linux ships with Deepin Desktop Environment (DDE) by default and Extension Manager handles GNOME Shell extensions. Can you confirm that you are running GNOME by running `echo $XDG_CURRENT_DESKTOP` command in a terminal?

**Comment by oscfdezdz** [comment]
See https://github.com/mjakeman/extension-manager/issues/452#issuecomment-2002009568
