### ISSUE TITLE
Can't find popular extensions

### ISSUE THREAD

**Issue by zilexa** [mjakeman/extension-manager#478]
**Describe the bug**
Simply searching "dash to panel" gives me results that don't even come close to this name. I searched for Dash to Panel (tried without any caps), ArcMenu and Gesture Improvements. But I could only find ArcMenu.
They all exist: 
- [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/)
- [Gesture Improvements](https://extensions.gnome.org/extension/4245/gesture-improvements/)
- [ArcMenu](https://extensions.gnome.org/extension/3628/arcmenu/)

**System Information:**
 - Distro OpenSUSE Tumblewee
 - Extension Manager 0.4.2
 - Package format (Flatpak, Snap, other) Flatpak

**Additional context**
Installed Extension Manager via Gnome Software (uses Flathub).

**Comment by binkobapkins** [comment]
Can confirm this as well on Ubuntu 22.04, using the .deb from the repos.
