### ISSUE TITLE
Search issue and crash

### ISSUE THREAD

**Issue by delyan-kirov** [mjakeman/extension-manager#482]
Support Log
----
Version: 0.4.2
Development: No
Package Format: Unknown Package
Status: Official
----
../src/exm-backtrace.c:79 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-browse-page.c:162 'refresh_search'
../src/exm-browse-page.c:198 'on_first_page_result'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:76 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'

**System Information**
 - Distro (Fedora)
 - Package format (Flatpak)

**Additional context**
The extension app does not find any extensions. It then crashes.

**Comment by mjakeman** [comment]
> ../src/web/exm-request-handler.c:76 'request_callback'

This is suspect - wonder if we're passing a null response from the web layer.

@delyan-kirov Could you try on the latest flatpak version (v0.4.3) and see if this is still a problem?

**Comment by delyan-kirov** [comment]
I was never able to reproduce this issue, but I've not had problems with it recently.
