### ISSUE TITLE
org.gnome.Platform 43 end of life

### ISSUE THREAD

**Issue by galen1423** [mjakeman/extension-manager#484]
Hello,

First of all, many thanks for your work; this tool is very useful.

Since few days, i have got this message when flatpak searching for software updates: 

`Looking for updates…
Info: org.gnome.Platform//43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.mattjakeman.ExtensionManager
`

Regards.

**Comment by oscfdezdz** [comment]
Hi,

Extension Manager has been using GNOME 44 runtime since version 0.4.2. If updating flatpaks does not update it, reinstalling should, if installed from [Flathub](https://flathub.org/apps/com.mattjakeman.ExtensionManager).

**Comment by galen1423** [comment]
Hi,

After reinstalled Extension manager from normal repository, error doesn't show anymore.

Regards
