### ISSUE TITLE
extension manager freeze then quit (sid)

### ISSUE THREAD

**Issue by toucanlord** [mjakeman/extension-manager#489]
Support Log
----
Version: 0.4.2
Development: No
Package Format: Unknown Package
Status: Official
----
../src/exm-backtrace.c:79 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-browse-page.c:162 'refresh_search'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/local/exm-manager.c:772 'on_state_changed'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/local/shell-dbus-interface.c:2756 'shell_extensions_proxy_g_signal'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'

**Comment by jo0oker-ah** [comment]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.207 was not provided by any .service files

**Comment by mjakeman** [comment]
It's not exactly the same, but let's track it in #640
