### ISSUE TITLE
Extension manager Could not check for updates

### ISSUE THREAD

**Issue by kinolex** [mjakeman/extension-manager#497]
*System Information:**
 - zorin os lite 
 - Extension Manager version (e.g. 0.4.2)
    Flatpak

**Comment by oscfdezdz** [comment]
Hi, Zorin OS Lite uses XFCE as desktop environment not GNOME, have you manually installed it?

**Comment by oscfdezdz** [comment]
Hi, Zorin OS Lite uses XFCE as desktop environment by default not GNOME, have you manually install it?

**Comment by oscfdezdz** [comment]
Duplicate of #452 as both distributions share default desktop environment.
