### ISSUE TITLE
[Feature request] Sort search by relevance

### ISSUE THREAD

**Issue by FelixFourcolor** [mjakeman/extension-manager#500]
EGO's default search method is by relevance, which in my experience provides much better results than other methods. Can you bring it to your program?

**Comment by oscfdezdz** [comment]
Hi, it was already added with 2ed4e19f09e3fb6d2de36b335f6dabb758a0b3ac.

**Comment by FelixFourcolor** [comment]
@oscfdezdz Apologies for not checking.
