### ISSUE TITLE
on new installation it closes

### ISSUE THREAD

**Issue by devfahadmunir** [mjakeman/extension-manager#501]
**Describe the bug**
A description of the bug goes here.

**System Information:**
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.4.2)
 - Package format (Flatpak, Snap, other)

**Additional context**

**Comment by oscfdezdz** [comment]
Hello, can you provide some details by filling out the issue template? So we can try to reproduce the error. Thanks.
