### ISSUE TITLE
"Use Extensions" switch head on the left even though it's switched on

### ISSUE THREAD

**Issue by Fxsch** [mjakeman/extension-manager#510]
**Describe the bug**
When opening Extension Manager, the `Use Extensions` switch is switched on but the switch head is on the left side, even though it should be on the right. Deactivating it and activating it again makes it look correct again until you reopen the app.

Screenshot:
![image](https://github.com/mjakeman/extension-manager/assets/77849217/a2a9a15e-dea8-4035-baef-a5088f608e19)

**System Information:**
 - **Distro:** EndeavourOS
 - **Extension Manager version:** 0.4.2
 - **Package format:** Flatpak

**Comment by oscfdezdz** [comment]
Hi, it should be fixed in latest version, 0.4.3, that was released two days ago.

**Comment by Fxsch** [comment]
Just tested it. Yes, it's fixed.
