### ISSUE TITLE
Feature Request: Enable page swipe gestures program wide

### ISSUE THREAD

**Issue by SaucySauce** [mjakeman/extension-manager#512]
DE: GNOME Shell 45, Wayland session.
Distribution: EndeavorOS
Device: MacBook Pro 8,1
Package source: Flatpak

As is the swipe gesture only works when the cursor is over the headerbar area, is this a feature or bug? On the About window the swipe gestures work perfectly regardless of where the cursor is located.

**Comment by oscfdezdz** [comment]
It may be an issue upstream, it works but if there is no scrollbar present. I could replicate with some core GNOME apps. For example, opening [this extension](https://extensions.gnome.org/extension/6198/light-style/) maximized on a large enough screen, it behaves as expected.

**Comment by mjakeman** [comment]
Related: #161 

Unfortunately, hasn't been much movement on this side. It's not something we can fix, but once GTK supports it we'll get it for free.

As this isn't actionable, I'll go ahead and close this issue - but yes we'll absolutely support it once we're able to.
