### ISSUE TITLE
Could not check for updates

### ISSUE THREAD

**Issue by JNewstedt** [mjakeman/extension-manager#513]
**Describe the bug**
From the error log:
`Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable`

**System Information:**
 - Distro Fedora 39 (KDE Plasma)
 - Version: 0.4.3
 - Development: No
 - Package Format: Unknown Package
 - Status: Official

**Additional context**
Tried to run for the first time and this popped up.

**Comment by mjakeman** [comment]
> Distro Fedora 39 (KDE Plasma)

Just to confirm, this is running under a GNOME Session and not KDE? But it's on the KDE Plasma spin of Fedora 39?

Could you please provide:
 * How did you install Extension Manager (flatpak or something else?)
 * How did you install GNOME?
 * Which version of GNOME are you using?
