### ISSUE TITLE
[WISH] Installed extensions list is not sorted - Info about install type (system, manual) is missing

### ISSUE THREAD

**Issue by ChrisLauinger77** [mjakeman/extension-manager#52]
The default extensions app has manually installed and system installed lists and inside the 2 lists the extensions are sorted by name.
IMHO there is no need for 2 lists. But the info if its systemwide installed could be shown in the list and also the list could be sorted alphabetically.

**Comment by bdaase** [comment]
This was already fixed in https://github.com/mjakeman/extension-manager/pull/15 and https://github.com/mjakeman/extension-manager/pull/17.

**Comment by ChrisLauinger77** [comment]
Sorry - seems not to be in the flatpak deployment (yet) ?

**Comment by bdaase** [comment]
Yeah, it's not released yet.

**Comment by ChrisLauinger77** [comment]
Thx 4 info
