### ISSUE TITLE
NameHasNoOwner error

### ISSUE THREAD

**Issue by matdave** [mjakeman/extension-manager#530]
**Describe the bug**

Unable to load extensions and all version in search say "Unsupported".

-------------------------------------------------

Support Log
----
Version: 0.4.3
Development: No
Package Format: Unknown Package
Status: Official
----
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: unit failed.

**System Information:**
 - Fedora 39 Asahi
 - Extension Manager version (e.g. 0.4.3)
 - Flatpak

**Additional context**
This started happening a couple days ago. Not sure if it was a recent update.

**Comment by mjakeman** [comment]
I'm running Fedora 39 Asahi with 0.5.1 and cannot reproduce this - hoping we've fixed it.

If the problem comes up again, please open another issue
