### ISSUE TITLE
Error/bug

### ISSUE THREAD

**Issue by Hanzla-Ashraf** [mjakeman/extension-manager#539]
**Describe the bug**
A description of the bug goes here.

**System Information:**
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.4.3)
 - Package format (Flatpak, Snap, other)

**Additional context**

**Comment by oscfdezdz** [comment]
Hi, we need some details about the error, could you please fill in the details of the issue template?
