### ISSUE TITLE
Meson error when building from source on Fedora 39 

### ISSUE THREAD

**Issue by shmu26** [mjakeman/extension-manager#543]
**Describe the bug**
When building from source I get this meson error:
```
meson setup _build
The Meson build system
Version: 1.2.3
Source dir: /home/shmuel/Downloads/extension-manager-0.4.3
Build dir: /home/shmuel/Downloads/extension-manager-0.4.3/_build
Build type: native build
Project name: extension-manager
Project version: 0.4.3
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)")
C linker for the host machine: cc ld.bfd 2.40-13
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring exm-config.h using configuration
Configuring com.mattjakeman.ExtensionManager.desktop.in using configuration
Program msgfmt found: YES (/usr/bin/msgfmt)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Configuring com.mattjakeman.ExtensionManager.metainfo.xml.in using configuration
Program appstreamcli found: YES (/usr/bin/appstreamcli)
Configuring com.mattjakeman.ExtensionManager.gschema.xml using configuration
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)

src/meson.build:32:22: ERROR: C shared or static library 'backtrace' not found

A full log can be found at [meson-log.txt](https://github.com/mjakeman/extension-manager/files/13726156/meson-log.txt)

```
log attached:
[meson-log.txt](https://github.com/mjakeman/extension-manager/files/13726220/meson-log.txt)

**System Information:**
 - Fedora Workstation 39 
 - Extension Manager version 0.4.3
 - Package format: source

**Additional context**
Obviously it would be better to install this from my distro's repo, but Fedora software center offers only a flatpak version, and I would prefer a native version.

**Comment by oscfdezdz** [comment]
Hello, you can either install libbacktrace from [source](https://github.com/ianlancetaylor/libbacktrace) or run `meson setup _build -Dbacktrace=false` instead.

**Comment by shmu26** [comment]
Thanks for your your reply. Now I get
```
meson setup _build -Dbacktrace=false
The Meson build system
Version: 1.2.3
Source dir: /home/shmuel/Downloads/extension-manager-0.4.3
Build dir: /home/shmuel/Downloads/extension-manager-0.4.3/_build
Build type: native build
Project name: extension-manager
Project version: 0.4.3
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)")
C linker for the host machine: cc ld.bfd 2.40-13
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring exm-config.h using configuration
Configuring com.mattjakeman.ExtensionManager.desktop.in using configuration
Program msgfmt found: YES (/usr/bin/msgfmt)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Configuring com.mattjakeman.ExtensionManager.metainfo.xml.in using configuration
Program appstreamcli found: YES (/usr/bin/appstreamcli)
Configuring com.mattjakeman.ExtensionManager.gschema.xml using configuration
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Library backtrace found: NO
Found pkg-config: /usr/bin/pkg-config (1.9.5)
Found CMake: /usr/bin/cmake (3.27.7)
Run-time dependency gtk4 found: NO (tried pkgconfig and cmake)

src/meson.build:35:2: ERROR: Dependency "gtk4" not found, tried pkgconfig and cmake

A full log can be found at /home/shmuel/Downloads/extension-manager-0.4.3/_build/meson-logs/meson-log.txt

```

**Comment by oscfdezdz** [comment]
Try installing `gtk4-devel`, other dependencies will also require to install their `-devel` package to build.

**Comment by shmu26** [comment]
Making progress but stuck on libsoup:
```
sudo dnf install libsoup-devel
Last metadata expiration check: 0:23:26 ago on Wed 20 Dec 2023 01:00:08 PM IST.
Package libsoup-devel-2.74.3-3.fc39.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
shmuel@fedora:~/Downloads/extension-manager-0.4.3$ meson setup _build -Dbacktrace=false
The Meson build system
Version: 1.2.3
Source dir: /home/shmuel/Downloads/extension-manager-0.4.3
Build dir: /home/shmuel/Downloads/extension-manager-0.4.3/_build
Build type: native build
Project name: extension-manager
Project version: 0.4.3
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)")
C linker for the host machine: cc ld.bfd 2.40-13
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring exm-config.h using configuration
Configuring com.mattjakeman.ExtensionManager.desktop.in using configuration
Program msgfmt found: YES (/usr/bin/msgfmt)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Configuring com.mattjakeman.ExtensionManager.metainfo.xml.in using configuration
Program appstreamcli found: YES (/usr/bin/appstreamcli)
Configuring com.mattjakeman.ExtensionManager.gschema.xml using configuration
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Library backtrace found: NO
Found pkg-config: /usr/bin/pkg-config (1.9.5)
Run-time dependency gtk4 found: YES 4.12.4
Run-time dependency libadwaita-1 found: YES 1.4.2
Run-time dependency gio-unix-2.0 found: YES 2.78.3
Run-time dependency json-glib-1.0 found: YES 1.8.0
Found CMake: /usr/bin/cmake (3.27.7)
Run-time dependency libsoup-3.0 found: NO (tried pkgconfig and cmake)

src/meson.build:39:2: ERROR: Dependency "libsoup-3.0" not found, tried pkgconfig and cmake

A full log can be found at /home/shmuel/Downloads/extension-manager-0.4.3/_build/meson-logs/meson-log.txt

```

**Comment by oscfdezdz** [comment]
It should be `libsoup3-devel`.

**Comment by shmu26** [comment]
Installed!
How do I run it?

**Comment by oscfdezdz** [comment]
That looks like you're missing [text-engine](https://github.com/mjakeman/text-engine/), you should be able to install it by running:

```
meson setup _build
ninja -C _build
ninja install -C _build
```

after cloning and the re-running:

```
ninja -C _build
ninja install -C _build
```

in extension-manager directory.

**Comment by oscfdezdz** [comment]
Maybe a reboot will help better, text-engine is a hard dependency that you already have to have installed, my bad.

**Comment by shmu26** [comment]
I am still getting that error after a reboot
`extension-manager: error while loading shared libraries: libtext-engine-0.1.so: cannot open shared object file: No such file or directory`

**Comment by shmu26** [comment]
This is the text-engine that I installed, I think you built it?
text-engine-0.1.1
Maybe I am using the wrong version?

**Comment by oscfdezdz** [comment]
> Maybe I am using the wrong version?

Yes, that's it. Checking the Flatpak manifest, it uses text-engine v0.1.0 for the stable version.

**Comment by oscfdezdz** [comment]
You can run `ninja -C _build uninstall`, although re-running `ninja -C _build` and `ninja -C _build install` with v0.1.0 should override it.

**Comment by shmu26** [comment]
Still same error, even after downgrading to v0.1.0 . Maybe it's a Wayland
issue or something.

**Comment by oscfdezdz** [comment]
I can reproduce the error in a new containerized F39 image.

**Comment by shmu26** [comment]
Thanks.
I can't quite figure out how to get a rpm package from that website. When I
click on the repo download button, instead of a download, I get a url that
says

[copr:copr.fedorainfracloud.org:0xmrtt:extension-manager]
name=Copr repo for extension-manager owned by 0xmrtt
baseurl=https://download.copr.fedorainfracloud.org/results/0xmrtt/extension-manager/fedora-$releasever-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/0xmrtt/extension-manager/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1

**Comment by oscfdezdz** [comment]
In Packages section select `text-engine`, the link of the first build id in table. There, in the table under Results, select chroot name `fedora-39-x86-64` and click `text-engine-0.1.1-1.fc38.x86_64.rpm` package, it should download it. This is the direct link if you prefer: https://download.copr.fedorainfracloud.org/results/0xmrtt/extension-manager/fedora-39-x86_64/04755785-text-engine/text-engine-0.1.1-1.fc38.x86_64.rpm
