### ISSUE TITLE
Build failed on manjaro

### ISSUE THREAD

**Issue by johnnydvc** [mjakeman/extension-manager#546]
**Describe the bug**
/usr/bin/blueprint-compiler batch-compile src/. ../extension-manager-0.4.3/src ../extension-manager-0.4.3/src/exm-window.blp ../extension-manager-0.4.3/src/exm-installed-page.blp ../extension-manager-0.4.3/src/exm-browse-page.blp ../extension-manager-0.4.3/src/exm-extension-row.blp ../extension-manager-0.4.3/src/exm-search-row.blp ../extension-manager-0.4.3/src/exm-detail-view.blp ../extension-manager-0.4.3/src/exm-screenshot.blp ../extension-manager-0.4.3/src/exm-comment-tile.blp ../extension-manager-0.4.3/src/exm-comment-dialog.blp ../extension-manager-0.4.3/src/exm-rating.blp ../extension-manager-0.4.3/src/exm-upgrade-assistant.blp ../extension-manager-0.4.3/src/exm-error-dialog.blp

error: Could not determine what kind of syntax is meant here
at ../extension-manager-0.4.3/src/exm-window.blp line 4 column 10:
   4 |template $ExmWindow : Adw.ApplicationWindow {
     |         ^

ninja: build stopped: subcommand failed.

**System Information:**
 - Manjaro
 - 0.4.3
 - Source

**Additional context**

**Comment by oscfdezdz** [comment]
It seems to be a problem with the blueprint version, make sure that `blueprint-compiler` is at least version 0.8.0. Although for version 0.4.3, it may require blueprint 0.10.0.

**Comment by mjakeman** [comment]
This is a packaging issue - I'd recommend asking the maintainer of the manjaro `blueprint-compiler` to upgrade that version to 0.10.0.

If you just want to use the app, flatpak is a good way to get it (and it's supported by us). Otherwise, this AUR package is well maintained: https://aur.archlinux.org/packages/extension-manager
