### ISSUE TITLE
An unexpected error occured

### ISSUE THREAD

**Issue by varshneydevansh** [mjakeman/extension-manager#551]
**Describe the bug**
An unexpected error occured

../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-application.c:94 'exm_application_activate'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

![image](https://github.com/mjakeman/extension-manager/assets/20411128/fdf2959e-f82c-40c9-84b9-1d9261426693)

**System Information:**
 - Distro **Ubuntu**
 - Package format ***Snap***

**Additional context**
[https://snapcraft.io/install/gnome-extension-manager/ubuntu](https://snapcraft.io/install/gnome-extension-manager/ubuntu)

**Comment by oscfdezdz** [comment]
Hi, Snap package is no longer supported, see https://github.com/mjakeman/extension-manager/issues/424#issuecomment-1636901997 and the linked comment there for more details.

**Comment by varshneydevansh** [comment]
Yeah! I found that a bit earlier and  just installed it using other package manager. Thank you for responding. =)
