### ISSUE TITLE
the extension settings do not open

### ISSUE THREAD

**Issue by cryptoproxy** [mjakeman/extension-manager#556]
**Describe the bug**
After restarting the device, I can open the extension settings for about 5 seconds, after which they close and I can't open them anymore.

**System Information:**
 - Distro: Fedora linux 39 workstation, gnome 45.3
 - Extension Manager version 0.4.3
 - Package format any

**Comment by oscfdezdz** [comment]
Hi, does the same thing happen with the Extensions application, does it happen with all extensions? I use the same distribution and version of Extensions Manager in Flatpak and I can't reproduce it.

**Comment by cryptoproxy** [comment]
> Hi, does the same thing happen with the Extensions app, does it happen with all extensions? I use the same distribution and version of Extensions Manager in Flatpak and I can't reproduce it.

yes, there is a problem with all extensions :(

**Comment by mjakeman** [comment]
Hi @cryptoproxy, if this is also happening with the GNOME Extensions app (the one with the green icon), I'd recommend filing an issue at https://gitlab.gnome.org/gnome/gnome-shell

This sounds like a GNOME Shell issue to me.
