### ISSUE TITLE
steam deck oled

### ISSUE THREAD

**Issue by bino8787** [mjakeman/extension-manager#564]
**Describe the bug**
A description of the bug goes here.

**System Information:**
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.4.3)
 - Package format (Flatpak, Snap, other)

**Additional context**

**Comment by bino8787** [comment]
i opened gnome app and got an issue

**Comment by oscfdezdz** [comment]
Hi, Steam Deck uses [KDE Plasma](https://kde.org/plasma-desktop/) as default desktop environment. Extension Manager is meant to manage [GNOME Shell](https://wiki.gnome.org/Projects/GnomeShell) extensions. Can you confirm that you are using GNOME Shell? And if so, fill in the template information so we can reproduce the error?

**Comment by mjakeman** [comment]
Closing - feel free to create a new issue with the requested information if this still happens
