### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Snoopy666** [mjakeman/extension-manager#569]
**Describe the bug**
A description of the bug goes here.

**System Information:**
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.4.3)
 - Package format (Flatpak, Snap, other)

**Additional context**

**Comment by oscfdezdz** [comment]
Hi, we need more information about the bug, could you complete the issue template to try to replicate it please?

**Comment by mjakeman** [comment]
Closing - feel free to create a new issue with the requested information if this still happens
