### ISSUE TITLE
Is the language file buggy?

### ISSUE THREAD

**Issue by ViBE-HU** [mjakeman/extension-manager#571]
**Describe the bug**
I just reviewed my translation cause nothing changed a long time and I still see untranslated strings while I already translated them and 0.4.3 version is out for a long time. I also noticed that POEdit merge line 243 to 244. Is that line misplaced or orphaned?

**System Information:**
 - Ubuntu 22.04
 - Extension Manager version 0.4.3
 - Flatpak

**Comment by oscfdezdz** [comment]
Translation template is a bit outdated, I've opened a merge request to update it. For version 0.4.3 some new strings were added shortly before the release, maybe that's why.
