### ISSUE TITLE
An eeror occured

### ISSUE THREAD

**Issue by spowerrr** [mjakeman/extension-manager#585]
**Describe the bug**
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.337 was not provided by any .service files

**System Information:**
 - Distro (debian)
 - Extension Manager version (latest)
 - Package format (Flatpak)

**Comment by spowerrr** [comment]
showing nothing in the app with no extensions

**Comment by oscfdezdz** [comment]
Which Debian version are you running? Also, which GNOME Shell version? You can check the latest in the Settings app or by running `gnome-shell --version` in a terminal.

**Comment by spowerrr** [comment]
> Which Debian version are you running? Also, which GNOME Shell version? You can check the latest in the Settings app or by running `gnome-shell --version` in a terminal.

debian 12 currently i'm using!
