### ISSUE TITLE
Fix implicit function declarations

### ISSUE THREAD

**Issue by jbicha** [mjakeman/extension-manager#590]
**Describe the bug**
Debian has recently made implicit function declarations [an error](https://wiki.debian.org/qa.debian.org/FTBFS#A2024-03-13_-Werror.3Dimplicit-function-declaration). This caused Debian's extension-manager 0.4.3 to fail to build.

**Additional context**
This failure can be duplicated if you set the compiler flag `-Werror=implicit-function-declaration`

This issue was originally reported at https://bugs.debian.org/1066393

**Comment by mjakeman** [comment]
Fixed this in #593 - I'll make sure it's in the 0.5.0 release I'm targeting for 18 March (GNOME 46 compatibility + other performance improvements). Should be fairly backport-able.
