### ISSUE TITLE
Publish to Flathub

### ISSUE THREAD

**Issue by mjakeman** [mjakeman/extension-manager#6]
Make the application available on flathub for ease of download. It has many other benefits like automatic updates, and should appear in GNOME Software for most users.

A few changes will need to be made for this:
 - Use GNOME SDK 41 instead of nightly
 - Bundle libadwaita as it is not present in the 41 SDK
 - Bundle gtk as libadwaita needs GTK 4.6 and the 41 SDK only provides 4.4

Are there any other specific requirements for being distributable on flathub?

**Comment by bdaase** [comment]
It's available 🎉
