### ISSUE TITLE
Bring back gnome versions supported by extension

### ISSUE THREAD

**Issue by dawidgarus** [mjakeman/extension-manager#604]
**Is your feature request related to a problem? Please describe.**
When new version of gnome is released, I want to know if all of the extensions I use were updated to support it, before I install gnome update.

**Describe the solution you'd like**
Bring back list of gnome versions that extension support on extension details page.

**Additional context**
No gnome versions visible after update:
![Screenshot from 2024-03-21 22-21-51](https://github.com/mjakeman/extension-manager/assets/6207659/9a40188e-1427-446b-929b-b1ac9b665cd1)

EDIT:
Alternatively, I would like to have some indicator next to an extension on installed list if I'm on older version of Gnome. Something like "This extension supports latest release of Gnome".

**Comment by oscfdezdz** [comment]
Upgrade Assistant, in main menu, should cover the use case you are describing. It shows you all your installed extensions and lets you choose the GNOME version to check compatibility against.

**Comment by dawidgarus** [comment]
My bad. I didn't know it exists. Closing the issue

**Comment by oscfdezdz** [comment]
Let us know if there's anything you'd improve in it 😄
