### ISSUE TITLE
missing NEWS.md

### ISSUE THREAD

**Issue by jbicha** [mjakeman/extension-manager#605]
NEWS.md was removed when the 0.5.0 release was prepared. Just checking if that was intentional.

**Comment by gabrbrand** [comment]
https://github.com/mjakeman/extension-manager/pull/592

> Re: The NEWS file, I've removed it as it's a pain to keep updating and since we aren't a library I think it has limited use. We keep track of this already in appdata and on github.

**Comment by mjakeman** [comment]
Hi, yes I did remove the NEWS file.

We already capture a "high level" release summary in [metainfo.xml](https://github.com/mjakeman/extension-manager/blob/master/data/com.mattjakeman.ExtensionManager.metainfo.xml.in.in) and a complete list of changes in the github [release notes](https://github.com/mjakeman/extension-manager/releases/tag/v0.5.0). 

Happy to reconsider if this is something you were depending on for packaging.

**Comment by jbicha** [comment]
It's not a blocker. Just checking. I'll close this now.
