### ISSUE TITLE
error report while istalling extension manager from flatpak

### ISSUE THREAD

**Issue by 301207parth** [mjakeman/extension-manager#611]
Support Log
----
Version: 0.5.0
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.1
Libadwaita: 1.5.0
----
../src/exm-backtrace.c:92 'exm_backtrace_print'
../src/main.c:42 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-detail-view.c:409 'on_data_loaded'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:80 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:110 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '_start'
(null):0 '(null)'

**Comment by mjakeman** [comment]
Seems like this is the same issue as #612
