### ISSUE TITLE
Crash during extension search

### ISSUE THREAD

**Issue by Navid-JL** [mjakeman/extension-manager#612]
Support Log
----
Version: 0.5.0
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.1
Libadwaita: 1.5.0
----
../src/exm-backtrace.c:92 'exm_backtrace_print'
../src/main.c:42 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-detail-view.c:409 'on_data_loaded'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:80 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:110 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '_start'
(null):0 '(null)'

**Comment by mjakeman** [comment]
This line is the problem: https://github.com/mjakeman/extension-manager/blob/7c301cf3182305a0b2000f3be943ca784a1a7cc3/src/exm-detail-view.c#L409

Looks like a crash when parsing the Shell version. We should add a bit more null checking here just in case.

@Navid-JL What extension were you searching for? Or was it just opening the browse page?

**Comment by Navid-JL** [comment]
@mjakeman it was the latter.

**Comment by CaptainMorgan12** [comment]
Have the same issue trying to open and unsupported extension "another sessions manager" after searching for it.

**Comment by CaptainMorgan12** [comment]
fixed with

`sudo apt install chrome-gnome-shell`

**Comment by Navid-JL** [comment]
> fixed with
> 
> `sudo apt install chrome-gnome-shell`

I'm not entirely sure if that would fix it as at the time of reporting this I'd already installed v10.1-5 of that package.

@mjakeman Since the opening of this issue, I haven't experienced any crashes. I'm running PopOS 22.04 - 6.8.0-76060800daily20240311-generic.

**Comment by CaptainMorgan12** [comment]
Sorry I should have clarified installing it fixed the issue for me with the same exact message.
