### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by dr-shift** [mjakeman/extension-manager#615]
../src/exm-backtrace.c:92 'exm_backtrace_print'
../src/main.c:42 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-detail-view.c:409 'on_data_loaded'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:80 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:110 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '_start'
(null):0 '(null)'

**Comment by oscfdezdz** [comment]
Duplicate of #612
