### ISSUE TITLE
Extension management

### ISSUE THREAD

**Issue by loover1** [mjakeman/extension-manager#628]
**Describe the bug**
A description of the bug goes here.
Support Log
----
Version: 0.5.0
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.1
Libadwaita: 1.5.0
**System Information:**
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.5.0)
 - Package format (Flatpak, Snap, other)

**Additional context**

**Comment by mjakeman** [comment]
Hi what specifically is the problem?
