### ISSUE TITLE
Build error: Namespace Adw does not contain a type called Dialog

### ISSUE THREAD

**Issue by johnnydvc** [mjakeman/extension-manager#629]
**Describe the bug**
Cannot build the package:

/usr/bin/blueprint-compiler batch-compile src/. ../extension-manager-0.5.0/src ../extension-manager-0.5.0/src/exm-window.blp ../extension-manager-0.5.0/src/exm-installed-page.blp ../extension-manager-0.5.0/src/exm-browse-page.blp ../extension-manager-0.5.0/src/exm-extension-row.blp ../extension-manager-0.5.0/src/exm-search-row.blp ../extension-manager-0.5.0/src/exm-detail-view.blp ../extension-manager-0.5.0/src/exm-screenshot.blp ../extension-manager-0.5.0/src/exm-comment-tile.blp ../extension-manager-0.5.0/src/exm-comment-dialog.blp ../extension-manager-0.5.0/src/exm-rating.blp ../extension-manager-0.5.0/src/exm-upgrade-assistant.blp ../extension-manager-0.5.0/src/exm-error-dialog.blp ../extension-manager-0.5.0/src/exm-info-bar.blp ../extension-manager-0.5.0/src/exm-info-bar-item.blp ../extension-manager-0.5.0/src/exm-screenshot-view.blp

error: Namespace Adw does not contain a type called Dialog
at ../extension-manager-0.5.0/src/exm-comment-dialog.blp line 4 column 34:
   4 |template $ExmCommentDialog : Adw.Dialog {
     |                                 ^
hint: Did you check your spelling?
hint: Are your dependencies up to date?

**System Information:**
 - 6.6.25-1-MANJARO 
 - E0.5.0-1
 - AUR

**Additional context**

**Comment by oscfdezdz** [comment]
Stable already ships libadwaita 1.5.0, so closing here.
