### ISSUE TITLE
Crashes on opening

### ISSUE THREAD

**Issue by ChildishGiant** [mjakeman/extension-manager#630]
**Describe the bug**
When I open the app nothing happens.

**System Information:**
 - Distro: Fedora 39
 - Extension Manager version: 0.5.0
 - Package format: Flatpak

**Additional context**
When I run the command used in the .desktop (`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=extension-manager --file-forwarding com.mattjakeman.ExtensionManager @@u %U @@`) I get this error: `extension-manager: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libgtk-4.so.1: invalid ELF header`

**Comment by oscfdezdz** [comment]
Try reinstalling by running `flatpak uninstall --delete-data com.mattjakeman.ExtensionManager` and `flatpak install com.mattjakeman.ExtensionManager`. Although with that error, it seems to me it's a runtime issue, do other Flatpak apps show this error?

**Comment by mjakeman** [comment]
Going to go ahead and close this - seems like a problem with flatpak.

If this is still happening for extension-manager, but not for other flatpak GTK apps, please open a new issue
