### ISSUE TITLE
Extension manager isn't opening

### ISSUE THREAD

**Issue by santa-christie** [mjakeman/extension-manager#631]
**Describe the bug**
The app isn't opening at all.

 - Ubuntu 22.4
 - Extension Manager version (0.4.0)
 - Snap
 
Additional Context : 
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

**Comment by oscfdezdz** [comment]
Snap has limitations for Extension Manager, use the deb or Flatpak packages instead. See https://github.com/mjakeman/extension-manager/issues/117#issuecomment-1636901291 for more details.
