### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Joyqbit** [mjakeman/extension-manager#633]
### System Information:
- Ubuntu 24.04 LTS
- Extension Manager version (e.g. 0.5.0)
- Package format: Flatpak

### Issue
../src/exm-backtrace.c:92 'exm_backtrace_print'
../src/main.c:42 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-comment-dialog.c:139 'on_get_comments'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:80 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:110 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '_start'
(null):0 '(null)'

**Comment by mjakeman** [comment]
Seems like the same issue as #496 - let's track it over there.

Duplicate of #496
