### ISSUE TITLE
LinuxAlma8.3: Dash to Panel Extension doesn't install , gives ERROR below.  Also extension searched all say "UNSUPPORTED" ???

### ISSUE THREAD

**Issue by FlackVanderdutch** [mjakeman/extension-manager#636]
Support Log
----
Version: 0.5.0
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.3
Libadwaita: 1.5.0
----
../src/exm-backtrace.c:92 'exm_backtrace_print'
../src/main.c:42 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-detail-view.c:409 'on_data_loaded'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:80 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:110 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '_start'
(null):0 '(null)'

**Comment by oscfdezdz** [comment]
Error is the same as https://github.com/mjakeman/extension-manager/issues/612 which is already fixed. Checking AlmaLinux packages versions in Repology, it looks like it's using GNOME 3.32, if that is the case, it won't work. Extension Manager supports versions 3.36 or above like the official Extensions app on Flathub.

**Comment by oscfdezdz** [comment]
Closing here, feel free to reopen if the version of GNOME Shell in Alma Linux 8.3, pointed out in my last comment, is wrong.
