### ISSUE TITLE
Allow installing extensions on unsupported version if `/org/gnome/shell/disable-extension-version-validation` is set

### ISSUE THREAD

**Issue by rmader** [mjakeman/extension-manager#64]
First of all: great app, thanks a lot - and congrats for the new release!

I'm a Mutter developer and thus run a development version of Mutter/Gnome-Shell most of the cycle as my daily driver - essentially dogfooding myself all the new features to help ensuring stability. As extensions usually only declare versions supported once a stable version was released, I have to run with `/org/gnome/shell/disable-extension-version-validation` enabled.
I'd love to use your app to try extensions from time to time, thus I'd like to humbly request to allow that if the setting above is set - maybe with some kind of visual warning.

**Comment by mjakeman** [comment]
Thanks!

I think this makes a lot of sense. For the mean time, I think it'll be fine to just skip the internal version check altogether (i.e. all buttons will show "Install"). Long term, I'd like to have an "unsupported but install anyway" state to make it very clear what is happening.

Something like this for the visual warning perhaps? Clicking on the button in the top-left would provide an informational message and instructions on how to disable the preference.

![image](https://user-images.githubusercontent.com/12368711/151143103-6e9eeff8-004e-440b-9ece-a23e62412ba2.png)

**Comment by mjakeman** [comment]
Extension Manager now supports installing out-of-date extensions.

There are a few caveats however; from the PR:

> Unfortunately, it is impossible to access gnome shell's version check gsettings key from within the sandbox. For now, let all users install 'unsupported' extensions as the reworked error handling will list them as out of date anyway. If the user manually overrides the disable-extension-version-validation preference, then Extension Manager will reflect those changes.

To have a more cohesive UI for this (and to support changing the preference from within the UI), we'll need buy-in from upstream. One idea is to see if it could be added to the Shell Extensions DBus API - would certainly make this more robust.


Here's a screenshot of the warning message at present:

![image](https://user-images.githubusercontent.com/12368711/159170242-08a3d746-a00a-464c-86a9-44696555b6f4.png)
