### ISSUE TITLE
Broken enable-toggle for unsupported extension

### ISSUE THREAD

**Issue by Eonfge** [mjakeman/extension-manager#65]
I discovered that installed but unsupported extensions, still have 'enable' toggles.

![Screenshot from 2022-01-24 16-46-27](https://user-images.githubusercontent.com/33983090/150815847-ed57e1f5-74b9-457e-b004-9a74b0a5b989.png)

To reproduce this issue, you can manually install an extension or you could use another tool to install an older version.

**Comment by mjakeman** [comment]
The enable/disable toggle is currently shown for all extensions rows regardless of whether the extension is compatible/loaded. We currently don't have access to that information, so the first step would be to handle extension load errors like the official app does.
