### ISSUE TITLE
Vitals - Ubuntu Studio 24.04 - fails during install

### ISSUE THREAD

**Issue by CoolGames** [mjakeman/extension-manager#650]
**Describe the bug**
A description of the bug goes here.
Attempted to install Vitals extension results in crash message suggesting not compatible with Gnome version.

**System Information:**
 - Distro Ubuntu Studio 24.04 - Fresh USB install May 5 2024
 - Extension Manager version 0.5.0-1build1
 - Package format - Apt install as per [Vitals by corecoding README.md](https://github.com/corecoding/Vitals)
 
**Additional context**
Issue also reported May 16 2024 to above github project.
System is 2014 System 76 lemu6 with i7 cpu and no added gpu.
The battery and AC adapter are showing age and need to be monitored during use continuously.

![Screenshot_20240517_073200](https://github.com/mjakeman/extension-manager/assets/149711/51993788-fc49-4962-b20a-36165762a32f)
[Vitals_24.04.txt](https://github.com/mjakeman/extension-manager/files/15348733/Vitals_24.04.txt)

**Comment by CoolGames** [comment]
After [reporting to extensions manager](https://github.com/mjakeman/extension-manager/issues/650) I again ran the steps to capture the error message here.
There may be an issue with [Ubuntu Studio 24.04 ](https://ubuntustudio.org/2024/04/ubuntu-studio-24-04-lts-released/) **_NON-SNAP build_** of extension manager.


![Vitals crash - Screenshot_20240517_080403](https://github.com/mjakeman/extension-manager/assets/149711/1a222dc8-836c-4bbb-8034-d21f132a5aee)

**Comment by oscfdezdz** [comment]
From Ubuntu Studio web (https://ubuntustudio.org/):

> Ubuntu Studio uses the Plasma Desktop by KDE

Extension Manager manages GNOME Shell extensions, so that is expected to happen.
