### ISSUE TITLE
Special character rendering in browser list view

### ISSUE THREAD

**Issue by Eonfge** [mjakeman/extension-manager#66]
There is a bug in the list-view when browsing applications. The HTML-escaped names are not properly displayed.

![Screenshot from 2022-01-24 16-49-59](https://user-images.githubusercontent.com/33983090/150816371-848200d2-9f52-4cfd-bed9-c62addb7eef6.png)

Do know that they show up properly in the next screen

![Screenshot from 2022-01-24 16-50-36](https://user-images.githubusercontent.com/33983090/150816430-fd0badad-34be-49ac-82bb-1ba3679e5fee.png)

**Comment by mjakeman** [comment]
Hmm, this is probably to do with GtkLabel's support for markup.

We're not escaping markup very consistently, so I imagine that is why it's broken only in some places.

Should be an easy fix, hopefully.
