### ISSUE TITLE
Window sizes are too small for contents

### ISSUE THREAD

**Issue by jrom99** [mjakeman/extension-manager#663]
**Describe the bug**

The default width and height of an extension settings dialog doesn't seem to be defined by its content, but more or less constant. Because of this, on most dialogs you have to scroll to see the see all settings, even if there is enough vertical space. However, the problem is more serious for horizontal space, since some windows require a bigger horizontal space then the default.

**System Information:**
 - Distro: Ubuntu 24.04 (GNOME 46 on Wayland)
 - Extension Manager version 0.5.0
 - Package format: apt

**Additional context**

Lack of vertical space:

![image](https://github.com/mjakeman/extension-manager/assets/47498278/e8af849d-a228-4a4d-a94c-bd99031c0ac3)

Lack of horizontal space:

![image](https://github.com/mjakeman/extension-manager/assets/47498278/0c336d5b-583d-406a-9938-f067828cca5d)

**Comment by oscfdezdz** [comment]
It is up to each extension to define the default size of its preference window. We do not modify that, if you want them to be different, you will have to propose it to the extension developer directly (See Details > Links > Homepage).

**Comment by jrom99** [comment]
That explanation doesn't really make sense, as this is not mentioned in the extension guide <https://gjs.guide/extensions/development/preferences.html> or documentation <https://gjs-docs.gnome.org/adw1/adw.preferenceswindow>

**Comment by oscfdezdz** [comment]
`height-request` and `width-request` from `GtkWidget` could also do the job.

**Comment by jrom99** [comment]
Trying to access https://gjs-docs.gnome.org/gtk40/gtk.window just shows a 404 error.

Again, I don't think this explanation makes sense. It is implied that the window should automatically take care of properties such as height and width, unless explicitly stated by the developer.

The default size should then be enough to:
1. show the available content and
2. not go outside the screen boundaries

Using a fixed height x width size that only respects (b) would be dumb UX, and having to manually specify them as a developer goes against programming for different screen resolutions.

**Comment by oscfdezdz** [comment]
> Trying to access https://gjs-docs.gnome.org/gtk40/gtk.window just shows a 404 error.

It's working here 🤔 

> Again, I don't think this explanation makes sense. It is implied that the window should automatically take care of properties such as height and width, unless explicitly stated by the developer.
> 
> The default size should then be enough to:
> 
>    1.  show the available content and
>    2. not go outside the screen boundaries
> 
> Using a fixed height x width size that only respects (b) would be dumb UX, and having to manually specify them as a developer goes against programming for different screen resolutions.

This is what I could find in the extension guide: https://gjs.guide/extensions/upgrading/gnome-shell-42.html#resize-preferences-window and in `AdwPreferencesWindow`'s source code: https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/adw-preferences-window.ui?ref_type=heads#L9-L10.

From the screenshots you posted earlier it looks like they both respect the default size of `AdwPreferencesWindow`. In the second screenshot it seems there are some issues in the extension's widget tree that causes that horizontal overflow. For the first, the vertical scrollbar is normal I guess.

We don't decide how the widgets work, that's up to GTK/Libadwaita and to open the extensions preferences windows, we make DBus calls if I recall correctly (on the GNOME Shell side).

**Comment by jrom99** [comment]
I'm still confused about this. The guide states:

>Preferences window no longer has a default size. `Adw.PreferencesWindow` can set the appropriate size by default.

And the docs state (for some weird reason the link doesn't open when you go from https://gjs-docs.gnome.org/adw1/adw.preferenceswindow, only when opened directly):

>The default size of a window is the size that will be used if no other constraints apply.
>
>If the window’s minimum size request is larger than the default, the default will be ignored.

Considering that the content is overflowing, the minimum size request should be bigger than the default, shouldn't it? This is unless the minimum size request is not sent by the app, which would mean that you should explicitly send this request via `window.set_default_size(-1, -1);` at the end of your `fillPreferencesWindow` function.

(Not to go on a tangent, but GTK function names are extremely dumb: `set_default_size` working as a resize function when `set_size` would be a lot more explicit is almost as bad as `gtk.colordialog.set_with_alpha`)

**Comment by oscfdezdz** [comment]
I agree that they seem a bit contradictory.

> Considering that the content is overflowing, the minimum size request should be bigger than the default, shouldn't it? This is unless the minimum size request is not sent by the app, which would mean that you should explicitly send this request via window.set_default_size(-1, -1); at the end of your fillPreferencesWindow function.

It should according to the guide, but in practice this doesn't seem to be the case and the default size of `AdwPreferencesWindow` is set in all cases. Requesting it via `window.set_default_size(-1, -1);` works but it seems to depend on the size requested by the widgets inside:

![image](https://github.com/mjakeman/extension-manager/assets/42654671/59b4bfaf-3d94-4cc0-bbb1-6f64e1165044)

It'll probably work for the first extension, since it uses newer widgets.

**Comment by jrom99** [comment]
Does that mean that a developer should manually set the size request for each and every widget so that the final window doesn't have vertical overflow?

**Comment by oscfdezdz** [comment]
No, it's specifically for the second extension that uses widgets that apparently require it.

**Comment by oscfdezdz** [comment]
Although it's already fixed in the master branch of the project 😄

**Comment by jrom99** [comment]
That's for horizontal overflow, right? And what should one do to avoid vertical overflow?

**Comment by oscfdezdz** [comment]
> That's for horizontal overflow, right?

Yes.

> And what should one do to avoid vertical overflow?

Proposing to set the `height-request` property of the window manually to the extension developers. Setting the value to -1, as you mentioned, should work.
