### ISSUE TITLE
crash on extension manager

### ISSUE THREAD

**Issue by Gaara710** [mjakeman/extension-manager#671]
Crash..
../src/exm-backtrace.c:107 'exm_backtrace_print'
../src/main.c:42 'handler'
41 frames omitted
../src/main.c:110 'run_app'
2 frames omitted
../sysdeps/x86_64/start.S:115 '_start'

**System Information:**
Fedora 40

**Additional context**
likely not a big deal, but figured I'd report the crash as instructed.

**Comment by oscfdezdz** [comment]
Duplicate of #644
