### ISSUE TITLE
Does not support/respect shell-theme

### ISSUE THREAD

**Issue by seanmrnda** [mjakeman/extension-manager#680]
**Describe the bug**
Does not support/respect shell themes.
**System Information:**
 - Distro: Fedora
 - Extension Manager version: v0.5.1
 - Package format: Flatpak
 - Shell-theme: Graphite

**Additional context**
 - Screenshot: 
![image](https://github.com/mjakeman/extension-manager/assets/45195351/b11fad62-8b67-4db2-bd5e-867f62eadfb9)

**Comment by mjakeman** [comment]
Hi, I'm not quite sure what you mean by Shell theme here.

If there's a problem with the User Themes extension specifically, you can file an issue with its maintainers [here](https://gitlab.gnome.org/GNOME/gnome-shell-extensions). This repo is for the extension manager tool only.

If you are asking about theming/customising Extension Manager, note that we use libadwaita. This means it doesn't theme conventionally (i.e. using CSS overrides). If you would like to customise the appearance of Extension Manager, you can use [Gradiance](https://github.com/GradienceTeam/Gradience).

**Comment by seanmrnda** [comment]
Thank you.
