### ISSUE TITLE
Fail to Use GNOME Extensions Manager and the browser

### ISSUE THREAD

**Issue by mdc-2468** [mjakeman/extension-manager#684]
I tried to activate gnome extensions, after
1. installed GNOME Shell
2. Tried on both firefox and chromium, installed GNOME Shell Integration extensions on both browser, 
still have an error of **Unable to locate GNOME Shell settings or version. Make sure it is installed and running.**

Note: my Extension manager is installed through flatpak

**System Information:**
 - Distro: Debian(bookwork 12)  with xfce
 - Extension Manager version: 0.5.1
 - GNOME Shell: 43.9
 - chrome-gnome-shell: 42.1-3

Support Log
----
 - Version: 0.5.1
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.4
Libadwaita: 1.5.1
----
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.120 was not provided by any .service files

**Comment by oscfdezdz** [comment]
It is expected, Extension Manager is for managing GNOME Shell extensions and does not work in Xfce or any other desktop environment. If you have GNOME Shell installed, select it before logging in and you will be able to use it normally.
