### ISSUE TITLE
all extinctions are unsupported on new genome v46 

### ISSUE THREAD

**Issue by mkabd666** [mjakeman/extension-manager#695]
now im running on nobara v40 and genome v46.

the problem that  all extensions are unsupported and the genome version is displayed as (null).

im new to linux so i dont know if i should downgrade the gnome version or what to do....

![Screenshot_٢٠٢٤٠٧٣٠_١٣١٩١٣](https://github.com/user-attachments/assets/89069efa-988c-4c1e-ada0-faa1ac6fc3ec)
![Screenshot_٢٠٢٤٠٧٣٠_١٣١٦٢٣](https://github.com/user-attachments/assets/9831f90a-9725-451c-be68-0e8dbb3aaf34)

**Comment by oscfdezdz** [comment]
It seems that the installation of GNOME is not correct or some distribution-specific package is missing. When you open the app, doesn't a warning appear at the bottom of the window indicating an error?

**Comment by mjakeman** [comment]
Feel free to open a new issue with the requested information^^
