### ISSUE TITLE
unexpected error occured in extension manager

### ISSUE THREAD

**Issue by siddharthsahu23** [mjakeman/extension-manager#699]
support Log
----
Version: 0.5.1
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.4
Libadwaita: 1.5.2
----
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.129 was not provided by any .service files

**Comment by oscfdezdz** [comment]
Make sure you are using GNOME, Extension Manager only supports extensions for its desktop environment, GNOME Shell, and no other.
