### ISSUE TITLE
Light/Dark Theme Switcher

### ISSUE THREAD

**Issue by mjakeman** [mjakeman/extension-manager#7]
Extension Manager respects the system dark preference. As that's not going to be widely available until GNOME 42, let's add an in-app toggle as well. As an added benefit, it will let the user override the system preference if they wish.

There's a very good implementation of this in the new Text Editor app. Maybe we can reuse some of it? See: https://gitlab.gnome.org/GNOME/gnome-text-editor

**Comment by bdaase** [comment]
Maybe it's enough to have a `Use dark theme` switch, as e.g., [easyeffects](https://github.com/wwmm/easyeffects)  does.
