### ISSUE TITLE
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Объект по пути «/org/gnome/Shell/Extensions» не существует

### ISSUE THREAD

**Issue by Haywnink** [mjakeman/extension-manager#700]
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Объект по пути «/org/gnome/Shell/Extensions» не существует

**Comment by oscfdezdz** [comment]
Duplicate of #699
