### ISSUE TITLE
Apply to replace Extensions app as a GNOME Core App

### ISSUE THREAD

**Issue by amethystgosling** [mjakeman/extension-manager#705]
**Is your feature request related to a problem? Please describe.**
This app makes the Extensions app obsolete so if this app becomes a core app by replacing the Extensions app, it'll be shipped to every GNOME user who updated to or installed the latest version, increasing the app's use. Users would only gain from this change because the app does everything the Extensions app does and much more.

**Describe the solution you'd like**
_Already given_

**Additional context**
I don't know if there are any complications with this but I thought I should ask.

**Comment by mjakeman** [comment]
Hey @amethystgosling

Unfortunately this isn't something in my control. I'd love to be part of GNOME more officially, but that is not up to me :)))

We are in the process of applying for GNOME Circle (#101) but that is taking a very long time, mainly as the design changes needed are significant, and I haven't have a whole lot of time to dedicate to this app this year.

I don't personally have any aspirations beyond GNOME Circle, but we'll see where the app ends up.

Glad you're enjoying it 😁
