### ISSUE TITLE
Stuck in black screen on launch

### ISSUE THREAD

**Issue by kaushiksahu18** [mjakeman/extension-manager#712]
**Describe the bug**
I am not able to use the app because after installing i am not able to launch the app, it stuck in black empty screen!

**System Information:**
 - Distro: Endeavrouos (arch linux)
 - Extension Manager version: 0.5.1-4
 - Package format: used **`yay`** to install pkg

**Additional context**
I dont know what to put here, but i can provide installation log if needed.

**Comment by oscfdezdz** [comment]
See https://github.com/mjakeman/extension-manager/issues/709#issuecomment-2323261308
