### ISSUE TITLE
error while installing extension manager in ubantu 18.04 LTS

### ISSUE THREAD

**Issue by kamlesh2** [mjakeman/extension-manager#713]
**System Information:**
Version: 0.5.1
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.4
Libadwaita: 1.5.3

Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Extensions was not provided by any .service files

**Comment by oscfdezdz** [comment]
Extension Manager requires GNOME 3.36 or higher. Ubuntu 18.04 uses GNOME 3.28 as far as I could find.

**Comment by oscfdezdz** [comment]
Duplicate of #318
