### ISSUE TITLE
When I have all the apps showing in the dashboard and I ask to lock the screen it blank the screen and asks to close session

### ISSUE THREAD

**Issue by hackroot9623** [mjakeman/extension-manager#715]
../src/exm-backtrace.c:107 'exm_backtrace_print'
../src/main.c:42 'handler'
2 frames omitted
../src/exm-browse-page.c:161 'refresh_search'
5 frames omitted
../src/local/exm-manager.c:778 'on_state_changed'
7 frames omitted
../src/local/shell-dbus-interface.c:2756 'shell_extensions_proxy_g_signal'
11 frames omitted
../src/main.c:110 'run_app'
2 frames omitted
../sysdeps/x86_64/start.S:115 '_start'

**Comment by oscfdezdz** [comment]
Closing this one in favor of #721 which has more context.
