### ISSUE TITLE
Cant turn on Extensions 

### ISSUE THREAD

**Issue by sid-vid** [mjakeman/extension-manager#723]
Support Log
----
Version: 0.5.1
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.5
Libadwaita: 1.5.4
----
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable

**Comment by oscfdezdz** [comment]
What distribution are you using? This error occurs when the desktop environment is not GNOME which is the environment that Extension Manager is made for.

**Comment by oscfdezdz** [comment]
Duplicate of #513
