### ISSUE TITLE
Not all extensions are shown

### ISSUE THREAD

**Issue by qux7** [mjakeman/extension-manager#724]
**Describe the bug**

Not all extensions are shown.
1. run `$ extension-manager`
2. type "static" into the search textbox
3. see the output. There is no way to scroll or go to the next page, so that's all 
![image](https://github.com/user-attachments/assets/c7311e21-4311-41cf-ae7b-dcdf6b6924f7)

4. select sorting by name
5. you will see different extensions, all starting with 'A' or 'B', and again, no way to have one more page 
![image](https://github.com/user-attachments/assets/496da1d9-c0f6-4973-b32b-2f5f6de6303b)

Expected: scrolling or normal pagination with navigation between pages (there must be many pages if the results do not fit onto one page)
Actual: only one page is shown

**System Information:**
 - Distro:  Ubuntu 22.04.3 LTS jammy (upgraded from 20.04, not a fresh install)
 - Extension Manager version:  0.5.1 according to https://flathub.org/apps/com.mattjakeman.ExtensionManager , but 0.3.0 according to the "About..." menu item
 - Package format: Flatpak

**Additional context**
The window on the image is tall, but when I make it shorter, a scrollbar appears, but anyway I cannot scroll to a next page.

**Comment by oscfdezdz** [comment]
Search underwent several changes not long ago that should be corrected in more recent versions. I recommend that you try the Flatpak package.

**Comment by oscfdezdz** [comment]
I am closing this issue as well since it should be fixed in newer versions, feel free to reopen it if you find any problems in those as well.
