### ISSUE TITLE
error in extension manager

### ISSUE THREAD

**Issue by Atchyuteswar** [mjakeman/extension-manager#726]
**Describe the bug**
../src/exm-backtrace.c:107 'exm_backtrace_print'
../src/main.c:42 'handler'
43 frames omitted
../src/main.c:110 'run_app'
2 frames omitted
../sysdeps/x86_64/start.S:115 '_start'

**System Information:**
 - Arch Linux
 - Extension Manager version (e.g. 0.5.1)
 - Flatpak

**Comment by oscfdezdz** [comment]
Duplicate of #644
