### ISSUE TITLE
Support Log

### ISSUE THREAD

**Issue by Migel1366** [mjakeman/extension-manager#734]
**Describe the bug**
A description of the bug goes here.

**System Information:**
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.5.1)
 - Package format (Flatpak, Snap, other)

**Additional context**

**Comment by oscfdezdz** [comment]
We need information about the error, could you please complete the template information?

**Comment by oscfdezdz** [comment]
Feel free to reopen the issue when you can provide the necessary information to reproduce the error.
