### ISSUE TITLE
Ubuntu 22.04 install higher version

### ISSUE THREAD

**Issue by Jai-GAY** [mjakeman/extension-manager#738]
How do I get[ the 0.5.1 version](https://github.com/mjakeman/extension-manager/releases) on my Ubuntu 22.04 64-bit Raspberry Pi 4B?

apt-get I can only get the 0.3.0 version.

```
sudo apt install gnome-shell-extension-manager
```
![Screenshot from 2024-11-12 15-57-18](https://github.com/user-attachments/assets/7fb243dc-1e77-4a02-86f3-7fefb6dddbc3)

**Comment by oscfdezdz** [comment]
See [README Installing section](https://github.com/mjakeman/extension-manager?tab=readme-ov-file#-installing).

**Comment by oscfdezdz** [comment]
Try `flatpak install -y flathub com.mattjakeman.ExtensionManager`. The runtime org.gnome.Platform/aarch64/46 should install automatically if not installed.

**Comment by Jai-GAY** [comment]
> Try `flatpak install -y flathub com.mattjakeman.ExtensionManager`

Noted, and thank you.
