### ISSUE TITLE
Accent Color Support

### ISSUE THREAD

**Issue by jhawkins002** [mjakeman/extension-manager#749]
**Describe the bug**
The current version of Extension Manager doesn't appear to honor Gnome's accent color settings for items like toggles, etc.

**System Information:**
 - Fedora 41
 - Extension Manager 0.5.1
 - Package format: Flatpak

**Additional context**
Could easily be seen as a bug or new feature, so feel free to reclassify if appropriate!

**Comment by sr66139p** [comment]
Having the same issue on Vanilla OS 2 with the Flatpak too

**Comment by oscfdezdz** [comment]
It will be fixed when we release the next version that will update the runtime to version 47. The planned date is December 6.

**Comment by oscfdezdz** [comment]
Version 0.6.0 is now available on Flathub.
