### ISSUE TITLE
List returns to top on pressing 'Load More Results'

### ISSUE THREAD

**Issue by RedAuburn** [mjakeman/extension-manager#753]
**Describe the bug**
On pressing Load More Results, the list returns to the top, resulting in the user needing to scroll to the bottom again and losing their place.

[Screencast From 2024-12-10 20-18-52.webm](https://github.com/user-attachments/assets/156a6658-d588-42d9-86fe-3dc0cd2622ba)

**System Information:**
 - Distro: Fedora 41 (fresh install)
 - Extension Manager version: 0.6.0
 - Package format: Flatpak

**Additional context**

**Comment by oscfdezdz** [comment]
This is probably due to commit 651fa4af20b408781cdc33a5df0823789c4acda4. Works for keyboard navigation but not for mouse, I will try to find an approach that works for both.
